/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApproverRouteImport } from './routes/approver'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as DeskValidatorRouteImport } from './routes/desk-validator'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as FieldOfficerRouteImport } from './routes/field-officer'
import { Route as FindMyLandRouteImport } from './routes/find-my-land'
import { Route as GisRouteImport } from './routes/gis'
import { Route as PiaRouteImport } from './routes/pia'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenDigitalizationsRouteImport } from './routes/citizen.digitalizations'
import { Route as CitizenLandDetailsRouteImport } from './routes/citizen.land-details'
import { Route as CitizenMyLandRouteImport } from './routes/citizen.my-land'
import { Route as CitizenMyLandMapRouteImport } from './routes/citizen.my-land-map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverRoute = ApproverRouteImport.update({
  id: '/approver',
  path: '/approver',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskValidatorRoute = DeskValidatorRouteImport.update({
  id: '/desk-validator',
  path: '/desk-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldOfficerRoute = FieldOfficerRouteImport.update({
  id: '/field-officer',
  path: '/field-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyLandRoute = FindMyLandRouteImport.update({
  id: '/find-my-land',
  path: '/find-my-land',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const PiaRoute = PiaRouteImport.update({
  id: '/pia',
  path: '/pia',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDigitalizationsRoute = CitizenDigitalizationsRouteImport.update({
  id: '/digitalizations',
  path: '/digitalizations',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenLandDetailsRoute = CitizenLandDetailsRouteImport.update({
  id: '/land-details',
  path: '/land-details',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyLandRoute = CitizenMyLandRouteImport.update({
  id: '/my-land',
  path: '/my-land',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyLandMapRoute = CitizenMyLandMapRouteImport.update({
  id: '/my-land-map',
  path: '/my-land-map',
  getParentRoute: () => CitizenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approver': typeof ApproverRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/desk-validator': typeof DeskValidatorRoute
  '/executive': typeof ExecutiveRoute
  '/field-officer': typeof FieldOfficerRoute
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/pia': typeof PiaRoute
  '/uploads': typeof UploadsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approver': typeof ApproverRoute
  '/desk-validator': typeof DeskValidatorRoute
  '/executive': typeof ExecutiveRoute
  '/field-officer': typeof FieldOfficerRoute
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/pia': typeof PiaRoute
  '/uploads': typeof UploadsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen': typeof CitizenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approver': typeof ApproverRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/desk-validator': typeof DeskValidatorRoute
  '/executive': typeof ExecutiveRoute
  '/field-officer': typeof FieldOfficerRoute
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/pia': typeof PiaRoute
  '/uploads': typeof UploadsRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approver'
    | '/citizen'
    | '/desk-validator'
    | '/executive'
    | '/field-officer'
    | '/find-my-land'
    | '/gis'
    | '/pia'
    | '/uploads'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/land-details'
    | '/citizen/my-land'
    | '/citizen/my-land-map'
    | '/citizen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approver'
    | '/desk-validator'
    | '/executive'
    | '/field-officer'
    | '/find-my-land'
    | '/gis'
    | '/pia'
    | '/uploads'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/land-details'
    | '/citizen/my-land'
    | '/citizen/my-land-map'
    | '/citizen'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approver'
    | '/citizen'
    | '/desk-validator'
    | '/executive'
    | '/field-officer'
    | '/find-my-land'
    | '/gis'
    | '/pia'
    | '/uploads'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/land-details'
    | '/citizen/my-land'
    | '/citizen/my-land-map'
    | '/citizen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApproverRoute: typeof ApproverRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  DeskValidatorRoute: typeof DeskValidatorRoute
  ExecutiveRoute: typeof ExecutiveRoute
  FieldOfficerRoute: typeof FieldOfficerRoute
  FindMyLandRoute: typeof FindMyLandRoute
  GisRoute: typeof GisRoute
  PiaRoute: typeof PiaRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver': {
      id: '/approver'
      path: '/approver'
      fullPath: '/approver'
      preLoaderRoute: typeof ApproverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk-validator': {
      id: '/desk-validator'
      path: '/desk-validator'
      fullPath: '/desk-validator'
      preLoaderRoute: typeof DeskValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-officer': {
      id: '/field-officer'
      path: '/field-officer'
      fullPath: '/field-officer'
      preLoaderRoute: typeof FieldOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-land': {
      id: '/find-my-land'
      path: '/find-my-land'
      fullPath: '/find-my-land'
      preLoaderRoute: typeof FindMyLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pia': {
      id: '/pia'
      path: '/pia'
      fullPath: '/pia'
      preLoaderRoute: typeof PiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/digitalizations': {
      id: '/citizen/digitalizations'
      path: '/digitalizations'
      fullPath: '/citizen/digitalizations'
      preLoaderRoute: typeof CitizenDigitalizationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/land-details': {
      id: '/citizen/land-details'
      path: '/land-details'
      fullPath: '/citizen/land-details'
      preLoaderRoute: typeof CitizenLandDetailsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-land': {
      id: '/citizen/my-land'
      path: '/my-land'
      fullPath: '/citizen/my-land'
      preLoaderRoute: typeof CitizenMyLandRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-land-map': {
      id: '/citizen/my-land-map'
      path: '/my-land-map'
      fullPath: '/citizen/my-land-map'
      preLoaderRoute: typeof CitizenMyLandMapRouteImport
      parentRoute: typeof CitizenRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenDigitalizationsRoute: typeof CitizenDigitalizationsRoute
  CitizenLandDetailsRoute: typeof CitizenLandDetailsRoute
  CitizenMyLandRoute: typeof CitizenMyLandRoute
  CitizenMyLandMapRoute: typeof CitizenMyLandMapRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenDigitalizationsRoute: CitizenDigitalizationsRoute,
  CitizenLandDetailsRoute: CitizenLandDetailsRoute,
  CitizenMyLandRoute: CitizenMyLandRoute,
  CitizenMyLandMapRoute: CitizenMyLandMapRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApproverRoute: ApproverRoute,
  CitizenRoute: CitizenRouteWithChildren,
  DeskValidatorRoute: DeskValidatorRoute,
  ExecutiveRoute: ExecutiveRoute,
  FieldOfficerRoute: FieldOfficerRoute,
  FindMyLandRoute: FindMyLandRoute,
  GisRoute: GisRoute,
  PiaRoute: PiaRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
