/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GisRouteImport } from './routes/gis'
import { Route as UploadsRouteImport } from './routes/uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gis' | '/uploads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gis' | '/uploads'
  id: '__root__' | '/' | '/gis' | '/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GisRoute: typeof GisRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GisRoute: GisRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
