/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as FindMyLandRouteImport } from './routes/find-my-land'
import { Route as GisRouteImport } from './routes/gis'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenAcquisitionRouteImport } from './routes/citizen.acquisition'
import { Route as CitizenAcquisitionStatusRouteImport } from './routes/citizen.acquisition-status'
import { Route as CitizenActivityRouteImport } from './routes/citizen.activity'
import { Route as CitizenCompensationRouteImport } from './routes/citizen.compensation'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenDigitalizationsRouteImport } from './routes/citizen.digitalizations'
import { Route as CitizenDigitizedRecordsRouteImport } from './routes/citizen.digitized-records'
import { Route as CitizenDocumentsRouteImport } from './routes/citizen.documents'
import { Route as CitizenFindLandRouteImport } from './routes/citizen.find-land'
import { Route as CitizenFindMyLandRouteImport } from './routes/citizen.find-my-land'
import { Route as CitizenLandAcquisitionRouteImport } from './routes/citizen.land-acquisition'
import { Route as CitizenLandDetailsRouteImport } from './routes/citizen.land-details'
import { Route as CitizenMyDocumentsRouteImport } from './routes/citizen.my-documents'
import { Route as CitizenMyLandRouteImport } from './routes/citizen.my-land'
import { Route as CitizenMyLandAcquisitionRouteImport } from './routes/citizen.my-land-acquisition'
import { Route as CitizenMyLandMapRouteImport } from './routes/citizen.my-land-map'
import { Route as CitizenNoticesRouteImport } from './routes/citizen.notices'
import { Route as CitizenPreferencesRouteImport } from './routes/citizen.preferences'
import { Route as CitizenProcessingStatusRouteImport } from './routes/citizen.processing-status'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenRehabilitationRouteImport } from './routes/citizen.rehabilitation'
import { Route as CitizenSecurityRouteImport } from './routes/citizen.security'
import { Route as CitizenSettingsRouteImport } from './routes/citizen.settings'
import { Route as CitizenSupportRouteImport } from './routes/citizen.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyLandRoute = FindMyLandRouteImport.update({
  id: '/find-my-land',
  path: '/find-my-land',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenAcquisitionRoute = CitizenAcquisitionRouteImport.update({
  id: '/acquisition',
  path: '/acquisition',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenAcquisitionStatusRoute =
  CitizenAcquisitionStatusRouteImport.update({
    id: '/acquisition-status',
    path: '/acquisition-status',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenActivityRoute = CitizenActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenCompensationRoute = CitizenCompensationRouteImport.update({
  id: '/compensation',
  path: '/compensation',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDigitalizationsRoute = CitizenDigitalizationsRouteImport.update({
  id: '/digitalizations',
  path: '/digitalizations',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDigitizedRecordsRoute = CitizenDigitizedRecordsRouteImport.update({
  id: '/digitized-records',
  path: '/digitized-records',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDocumentsRoute = CitizenDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenFindLandRoute = CitizenFindLandRouteImport.update({
  id: '/find-land',
  path: '/find-land',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenFindMyLandRoute = CitizenFindMyLandRouteImport.update({
  id: '/find-my-land',
  path: '/find-my-land',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenLandAcquisitionRoute = CitizenLandAcquisitionRouteImport.update({
  id: '/land-acquisition',
  path: '/land-acquisition',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenLandDetailsRoute = CitizenLandDetailsRouteImport.update({
  id: '/land-details',
  path: '/land-details',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyDocumentsRoute = CitizenMyDocumentsRouteImport.update({
  id: '/my-documents',
  path: '/my-documents',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyLandRoute = CitizenMyLandRouteImport.update({
  id: '/my-land',
  path: '/my-land',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyLandAcquisitionRoute =
  CitizenMyLandAcquisitionRouteImport.update({
    id: '/my-land-acquisition',
    path: '/my-land-acquisition',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenMyLandMapRoute = CitizenMyLandMapRouteImport.update({
  id: '/my-land-map',
  path: '/my-land-map',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNoticesRoute = CitizenNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenPreferencesRoute = CitizenPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProcessingStatusRoute = CitizenProcessingStatusRouteImport.update({
  id: '/processing-status',
  path: '/processing-status',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenRehabilitationRoute = CitizenRehabilitationRouteImport.update({
  id: '/rehabilitation',
  path: '/rehabilitation',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSecurityRoute = CitizenSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSettingsRoute = CitizenSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSupportRoute = CitizenSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CitizenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
  '/citizen/acquisition': typeof CitizenAcquisitionRoute
  '/citizen/acquisition-status': typeof CitizenAcquisitionStatusRoute
  '/citizen/activity': typeof CitizenActivityRoute
  '/citizen/compensation': typeof CitizenCompensationRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/digitized-records': typeof CitizenDigitizedRecordsRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/find-land': typeof CitizenFindLandRoute
  '/citizen/find-my-land': typeof CitizenFindMyLandRoute
  '/citizen/land-acquisition': typeof CitizenLandAcquisitionRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-documents': typeof CitizenMyDocumentsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-acquisition': typeof CitizenMyLandAcquisitionRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen/notices': typeof CitizenNoticesRoute
  '/citizen/preferences': typeof CitizenPreferencesRoute
  '/citizen/processing-status': typeof CitizenProcessingStatusRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rehabilitation': typeof CitizenRehabilitationRoute
  '/citizen/security': typeof CitizenSecurityRoute
  '/citizen/settings': typeof CitizenSettingsRoute
  '/citizen/support': typeof CitizenSupportRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
  '/citizen/acquisition': typeof CitizenAcquisitionRoute
  '/citizen/acquisition-status': typeof CitizenAcquisitionStatusRoute
  '/citizen/activity': typeof CitizenActivityRoute
  '/citizen/compensation': typeof CitizenCompensationRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/digitized-records': typeof CitizenDigitizedRecordsRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/find-land': typeof CitizenFindLandRoute
  '/citizen/find-my-land': typeof CitizenFindMyLandRoute
  '/citizen/land-acquisition': typeof CitizenLandAcquisitionRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-documents': typeof CitizenMyDocumentsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-acquisition': typeof CitizenMyLandAcquisitionRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen/notices': typeof CitizenNoticesRoute
  '/citizen/preferences': typeof CitizenPreferencesRoute
  '/citizen/processing-status': typeof CitizenProcessingStatusRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rehabilitation': typeof CitizenRehabilitationRoute
  '/citizen/security': typeof CitizenSecurityRoute
  '/citizen/settings': typeof CitizenSettingsRoute
  '/citizen/support': typeof CitizenSupportRoute
  '/citizen': typeof CitizenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/find-my-land': typeof FindMyLandRoute
  '/gis': typeof GisRoute
  '/uploads': typeof UploadsRoute
  '/citizen/acquisition': typeof CitizenAcquisitionRoute
  '/citizen/acquisition-status': typeof CitizenAcquisitionStatusRoute
  '/citizen/activity': typeof CitizenActivityRoute
  '/citizen/compensation': typeof CitizenCompensationRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/digitalizations': typeof CitizenDigitalizationsRoute
  '/citizen/digitized-records': typeof CitizenDigitizedRecordsRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/find-land': typeof CitizenFindLandRoute
  '/citizen/find-my-land': typeof CitizenFindMyLandRoute
  '/citizen/land-acquisition': typeof CitizenLandAcquisitionRoute
  '/citizen/land-details': typeof CitizenLandDetailsRoute
  '/citizen/my-documents': typeof CitizenMyDocumentsRoute
  '/citizen/my-land': typeof CitizenMyLandRoute
  '/citizen/my-land-acquisition': typeof CitizenMyLandAcquisitionRoute
  '/citizen/my-land-map': typeof CitizenMyLandMapRoute
  '/citizen/notices': typeof CitizenNoticesRoute
  '/citizen/preferences': typeof CitizenPreferencesRoute
  '/citizen/processing-status': typeof CitizenProcessingStatusRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/rehabilitation': typeof CitizenRehabilitationRoute
  '/citizen/security': typeof CitizenSecurityRoute
  '/citizen/settings': typeof CitizenSettingsRoute
  '/citizen/support': typeof CitizenSupportRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/find-my-land'
    | '/gis'
    | '/uploads'
    | '/citizen/acquisition'
    | '/citizen/acquisition-status'
    | '/citizen/activity'
    | '/citizen/compensation'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/digitized-records'
    | '/citizen/documents'
    | '/citizen/find-land'
    | '/citizen/find-my-land'
    | '/citizen/land-acquisition'
    | '/citizen/land-details'
    | '/citizen/my-documents'
    | '/citizen/my-land'
    | '/citizen/my-land-acquisition'
    | '/citizen/my-land-map'
    | '/citizen/notices'
    | '/citizen/preferences'
    | '/citizen/processing-status'
    | '/citizen/profile'
    | '/citizen/rehabilitation'
    | '/citizen/security'
    | '/citizen/settings'
    | '/citizen/support'
    | '/citizen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-my-land'
    | '/gis'
    | '/uploads'
    | '/citizen/acquisition'
    | '/citizen/acquisition-status'
    | '/citizen/activity'
    | '/citizen/compensation'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/digitized-records'
    | '/citizen/documents'
    | '/citizen/find-land'
    | '/citizen/find-my-land'
    | '/citizen/land-acquisition'
    | '/citizen/land-details'
    | '/citizen/my-documents'
    | '/citizen/my-land'
    | '/citizen/my-land-acquisition'
    | '/citizen/my-land-map'
    | '/citizen/notices'
    | '/citizen/preferences'
    | '/citizen/processing-status'
    | '/citizen/profile'
    | '/citizen/rehabilitation'
    | '/citizen/security'
    | '/citizen/settings'
    | '/citizen/support'
    | '/citizen'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/find-my-land'
    | '/gis'
    | '/uploads'
    | '/citizen/acquisition'
    | '/citizen/acquisition-status'
    | '/citizen/activity'
    | '/citizen/compensation'
    | '/citizen/dashboard'
    | '/citizen/digitalizations'
    | '/citizen/digitized-records'
    | '/citizen/documents'
    | '/citizen/find-land'
    | '/citizen/find-my-land'
    | '/citizen/land-acquisition'
    | '/citizen/land-details'
    | '/citizen/my-documents'
    | '/citizen/my-land'
    | '/citizen/my-land-acquisition'
    | '/citizen/my-land-map'
    | '/citizen/notices'
    | '/citizen/preferences'
    | '/citizen/processing-status'
    | '/citizen/profile'
    | '/citizen/rehabilitation'
    | '/citizen/security'
    | '/citizen/settings'
    | '/citizen/support'
    | '/citizen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  FindMyLandRoute: typeof FindMyLandRoute
  GisRoute: typeof GisRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-land': {
      id: '/find-my-land'
      path: '/find-my-land'
      fullPath: '/find-my-land'
      preLoaderRoute: typeof FindMyLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/acquisition': {
      id: '/citizen/acquisition'
      path: '/acquisition'
      fullPath: '/citizen/acquisition'
      preLoaderRoute: typeof CitizenAcquisitionRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/acquisition-status': {
      id: '/citizen/acquisition-status'
      path: '/acquisition-status'
      fullPath: '/citizen/acquisition-status'
      preLoaderRoute: typeof CitizenAcquisitionStatusRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/activity': {
      id: '/citizen/activity'
      path: '/activity'
      fullPath: '/citizen/activity'
      preLoaderRoute: typeof CitizenActivityRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/compensation': {
      id: '/citizen/compensation'
      path: '/compensation'
      fullPath: '/citizen/compensation'
      preLoaderRoute: typeof CitizenCompensationRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/digitalizations': {
      id: '/citizen/digitalizations'
      path: '/digitalizations'
      fullPath: '/citizen/digitalizations'
      preLoaderRoute: typeof CitizenDigitalizationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/digitized-records': {
      id: '/citizen/digitized-records'
      path: '/digitized-records'
      fullPath: '/citizen/digitized-records'
      preLoaderRoute: typeof CitizenDigitizedRecordsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/documents': {
      id: '/citizen/documents'
      path: '/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof CitizenDocumentsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/find-land': {
      id: '/citizen/find-land'
      path: '/find-land'
      fullPath: '/citizen/find-land'
      preLoaderRoute: typeof CitizenFindLandRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/find-my-land': {
      id: '/citizen/find-my-land'
      path: '/find-my-land'
      fullPath: '/citizen/find-my-land'
      preLoaderRoute: typeof CitizenFindMyLandRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/land-acquisition': {
      id: '/citizen/land-acquisition'
      path: '/land-acquisition'
      fullPath: '/citizen/land-acquisition'
      preLoaderRoute: typeof CitizenLandAcquisitionRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/land-details': {
      id: '/citizen/land-details'
      path: '/land-details'
      fullPath: '/citizen/land-details'
      preLoaderRoute: typeof CitizenLandDetailsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-documents': {
      id: '/citizen/my-documents'
      path: '/my-documents'
      fullPath: '/citizen/my-documents'
      preLoaderRoute: typeof CitizenMyDocumentsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-land': {
      id: '/citizen/my-land'
      path: '/my-land'
      fullPath: '/citizen/my-land'
      preLoaderRoute: typeof CitizenMyLandRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-land-acquisition': {
      id: '/citizen/my-land-acquisition'
      path: '/my-land-acquisition'
      fullPath: '/citizen/my-land-acquisition'
      preLoaderRoute: typeof CitizenMyLandAcquisitionRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-land-map': {
      id: '/citizen/my-land-map'
      path: '/my-land-map'
      fullPath: '/citizen/my-land-map'
      preLoaderRoute: typeof CitizenMyLandMapRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notices': {
      id: '/citizen/notices'
      path: '/notices'
      fullPath: '/citizen/notices'
      preLoaderRoute: typeof CitizenNoticesRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/preferences': {
      id: '/citizen/preferences'
      path: '/preferences'
      fullPath: '/citizen/preferences'
      preLoaderRoute: typeof CitizenPreferencesRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/processing-status': {
      id: '/citizen/processing-status'
      path: '/processing-status'
      fullPath: '/citizen/processing-status'
      preLoaderRoute: typeof CitizenProcessingStatusRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/rehabilitation': {
      id: '/citizen/rehabilitation'
      path: '/rehabilitation'
      fullPath: '/citizen/rehabilitation'
      preLoaderRoute: typeof CitizenRehabilitationRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/security': {
      id: '/citizen/security'
      path: '/security'
      fullPath: '/citizen/security'
      preLoaderRoute: typeof CitizenSecurityRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/settings': {
      id: '/citizen/settings'
      path: '/settings'
      fullPath: '/citizen/settings'
      preLoaderRoute: typeof CitizenSettingsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/support': {
      id: '/citizen/support'
      path: '/support'
      fullPath: '/citizen/support'
      preLoaderRoute: typeof CitizenSupportRouteImport
      parentRoute: typeof CitizenRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenAcquisitionRoute: typeof CitizenAcquisitionRoute
  CitizenAcquisitionStatusRoute: typeof CitizenAcquisitionStatusRoute
  CitizenActivityRoute: typeof CitizenActivityRoute
  CitizenCompensationRoute: typeof CitizenCompensationRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenDigitalizationsRoute: typeof CitizenDigitalizationsRoute
  CitizenDigitizedRecordsRoute: typeof CitizenDigitizedRecordsRoute
  CitizenDocumentsRoute: typeof CitizenDocumentsRoute
  CitizenFindLandRoute: typeof CitizenFindLandRoute
  CitizenFindMyLandRoute: typeof CitizenFindMyLandRoute
  CitizenLandAcquisitionRoute: typeof CitizenLandAcquisitionRoute
  CitizenLandDetailsRoute: typeof CitizenLandDetailsRoute
  CitizenMyDocumentsRoute: typeof CitizenMyDocumentsRoute
  CitizenMyLandRoute: typeof CitizenMyLandRoute
  CitizenMyLandAcquisitionRoute: typeof CitizenMyLandAcquisitionRoute
  CitizenMyLandMapRoute: typeof CitizenMyLandMapRoute
  CitizenNoticesRoute: typeof CitizenNoticesRoute
  CitizenPreferencesRoute: typeof CitizenPreferencesRoute
  CitizenProcessingStatusRoute: typeof CitizenProcessingStatusRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenRehabilitationRoute: typeof CitizenRehabilitationRoute
  CitizenSecurityRoute: typeof CitizenSecurityRoute
  CitizenSettingsRoute: typeof CitizenSettingsRoute
  CitizenSupportRoute: typeof CitizenSupportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenAcquisitionRoute: CitizenAcquisitionRoute,
  CitizenAcquisitionStatusRoute: CitizenAcquisitionStatusRoute,
  CitizenActivityRoute: CitizenActivityRoute,
  CitizenCompensationRoute: CitizenCompensationRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenDigitalizationsRoute: CitizenDigitalizationsRoute,
  CitizenDigitizedRecordsRoute: CitizenDigitizedRecordsRoute,
  CitizenDocumentsRoute: CitizenDocumentsRoute,
  CitizenFindLandRoute: CitizenFindLandRoute,
  CitizenFindMyLandRoute: CitizenFindMyLandRoute,
  CitizenLandAcquisitionRoute: CitizenLandAcquisitionRoute,
  CitizenLandDetailsRoute: CitizenLandDetailsRoute,
  CitizenMyDocumentsRoute: CitizenMyDocumentsRoute,
  CitizenMyLandRoute: CitizenMyLandRoute,
  CitizenMyLandAcquisitionRoute: CitizenMyLandAcquisitionRoute,
  CitizenMyLandMapRoute: CitizenMyLandMapRoute,
  CitizenNoticesRoute: CitizenNoticesRoute,
  CitizenPreferencesRoute: CitizenPreferencesRoute,
  CitizenProcessingStatusRoute: CitizenProcessingStatusRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenRehabilitationRoute: CitizenRehabilitationRoute,
  CitizenSecurityRoute: CitizenSecurityRoute,
  CitizenSettingsRoute: CitizenSettingsRoute,
  CitizenSupportRoute: CitizenSupportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  FindMyLandRoute: FindMyLandRoute,
  GisRoute: GisRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
