import { PersonaInfo, KeyModuleInfo, ProblemSolutionStep, LandRecordStatus } from './types';

export const HERO_CONTENT = {
  tagline: {
    en: 'Bringing Clarity to Land Acquisition and Records',
    hi: 'भूमि अधिग्रहण एवं अभिलेखों में पारदर्शिता और स्पष्टता',
    bn: 'ভূমি অর্জন ও রেকর্ডে স্বচ্ছতা ও স্পষ্টতা আনা',
  },
  missionStatement: {
    en: 'A unified, AI-driven platform for end-to-end land acquisition monitoring and intelligent land-record digitization',
    hi: 'संपूर्ण भूमि अधिग्रहण निगरानी एवं बौद्धिक भू-अभिलेख डिजिटलीकरण हेतु एक एकीकृत, एआई-संचालित राष्ट्रीय मंच',
    bn: 'সর্বস্তরের ভূমি অর্জন নিরীক্ষণ ও বুদ্ধিমান ভূমি রেকর্ড ডিজিটাইজেশনের জন্য একটি একীভূত, এআই-চালিত জাতীয় প্ল্যাটফর্ম',
  },
  officialCta: {
    en: 'Official Login',
    hi: 'अधिकारी लॉगिन',
    bn: 'আধিকারিক লগইন',
  },
  officialCtaSub: {
    en: 'For PIAs, LAOs, CALA & District Magistrates',
    hi: 'पीआईए, एलएओ, सीएएलए एवं जिलाधिकारियों हेतु',
    bn: 'পিআইএ, এলএও, সিএএলএ এবং জেলা মেজিস্ট্রেটদের জন্য',
  },
  citizenCta: {
    en: 'Start Uploading',
    hi: 'शुरू करें अपलोडिंग',
    bn: 'আপলোডিং শুরু করুন',
  },
  citizenCtaSub: {
    en: 'Instant Khasra & Compensation Tracker',
    hi: 'खसरा एवं मुआवजा प्रत्यक्ष ट्रैकर',
    bn: 'তাৎক্ষণিক খসরা ও ক্ষতিপূরণ ট্র্যাকার',
  },
};

export const TRUST_PARTNERS = [
  {
    name: 'DILRMP 2.0',
    title: 'Digital India Land Records Modernization',
    titleHi: 'डिजिटल इंडिया भूमि अभिलेख आधुनिकीकरण कार्यक्रम',
    titleBn: 'ডিজিটাল ইন্ডিয়া ভূমি রেকর্ড আধুনিকীকরণ প্রোগ্রাম',
    badge: 'National Program',
    badgeHi: 'राष्ट्रीय कार्यक्रम',
    badgeBn: 'জাতীয় প্রোগ্রাম',
    type: 'Core Framework',
  },
  {
    name: 'LRMS Integration',
    title: 'Unified State Land Records Management System',
    titleHi: 'एकीकृत राज्य भू-अभिलेख प्रबंधन प्रणाली',
    titleBn: 'একীকৃত রাজ্য ভূমি রেকর্ড ম্যানেজমেন্ট সিস্টেম',
    badge: '28 States Synced',
    badgeHi: '28 राज्य एकीकृत',
    badgeBn: '২৮ রাজ্য সিঙ্কড',
    type: 'API Gateway',
  },
  {
    name: 'Ministry of Rural Development',
    title: 'Department of Land Resources (DoLR)',
    titleHi: 'ग्रामीण विकास मंत्रालय (भूमि संसाधन विभाग)',
    titleBn: 'গ্রামীন উন্নয়ন মন্ত্রণালয় (ভূমি সম্পদ বিভাগ)',
    badge: 'Nodal Ministry',
    badgeHi: 'नोडल मंत्रालय',
    badgeBn: 'নোডাল মন্ত্রণালয়',
    type: 'Governance',
  },
  {
    name: 'NIC Cloud MeghRaj',
    title: 'National Informatics Centre Infrastructure',
    titleHi: 'राष्ट्रीय सूचना विज्ञान केंद्र (एनआईसी)',
    titleBn: 'জাতীয় তথ্য বিজ্ঞান কেন্দ্র (এনআইসি) 인ফ্রাস্ট্রাকচার',
    badge: 'Tier-IV Secure',
    badgeHi: 'टियर-4 सुरक्षित',
    badgeBn: 'টিয়ার-IV সুরক্ষিত',
    type: 'Secure Cloud',
  },
  {
    name: 'Bhunaksha & GIS Sync',
    title: 'Survey of India & Cadastral Mapping Grid',
    titleHi: 'भू-नक्शा एवं स्थानिक भू-मानचित्रण ग्रिड',
    titleBn: 'ভারতের সার্ভে এবং ক্যাডাস্ট্রাল ম্যাপিং গ্রিড',
    badge: 'Spatial Engine',
    badgeHi: 'स्थानिक इंजन',
    badgeBn: 'স্থানিক ইঞ্জিন',
    type: 'GIS Registry',
  },
];

export const PROBLEM_SOLUTION_STEPS: ProblemSolutionStep[] = [
  {
    stepNumber: '01',
    title: 'Fragmented Records',
    titleHi: 'अव्यवस्थित एवं खंडित अभिलेख',
    titleBn: 'অव्यবস্থাপিত ও খণ্ডিত রেকর্ড',
    tag: 'Legacy Challenge',
    tagHi: 'पारंपरिक समस्या',
    tagBn: 'ঐতিহাসিক সমস্যা',
    points: [
      'Disparate paper RoRs across states (Jamabandi, Khatoni, 7/12, Patta).',
      'Un-reconciled boundary demarcations leading to prolonged civil litigation.',
      'Manual, opaque compensation calculation causing citizen distrust.',
    ],
    pointsHi: [
      'विभिन्न राज्यों में अलग-अलग प्रारूप (जमाबंदी, खतौनी, 7/12, पट्टा)।',
      'अस्पष्ट सीमांकन जिससे वर्षों तक कानूनी विवाद एवं परियोजना विलंब।',
      'मैन्युअल और अपारदर्शी मुआवजा गणना प्रणाली।',
    ],
    pointsBn: [
      'বিভিন্ন রাজ্যে বিভিন্ন ফরম্যাটে রেকর্ড (জমাবন্দি, খতিয়ান, ৭/১২, পট্টা)।',
      'অস্পষ্ট সীমানির্ধারণ যেটি বছরের পর বছর লീগ্যাল বিবাদ ও প্রকল্প বিলম্বের কারণ।',
      'ম্যানুয়াল ও অপারদর্শী ক্ষতিপূরণ গণনা পদ্ধতি।',
    ],
    icon: 'Layers',
    statusBadge: 'Legacy Burden',
    statusBadgeHi: 'पारंपरिक बाधा',
    statusBadgeBn: 'ঐতিহাসিক বাধা',
    color: 'amber',
  },
  {
    stepNumber: '02',
    title: 'AI Digitization & OCR',
    titleHi: 'एआई डिजिटलीकरण एवं ओसीआर',
    titleBn: 'এআই ডিজিটাইজেশন ও ওসিআর',
    tag: 'ZameenAI Core Engine',
    tagHi: 'ज़मीन एआई मुख्य इंजन',
    tagBn: 'জামিন এআই কোর ইঞ্জিন',
    points: [
      'Multilingual neural OCR for complex vernacular handwritten revenue records.',
      'Automated semantic validation cross-checking deeds against encumbrance certificates.',
      'Geo-rectification aligning satellite imagery with vector cadastral parcels.',
    ],
    pointsHi: [
      'हस्तलिखित क्षेत्रीय राजस्व अभिलेखों हेतु बहुभाषी न्यूरल ओसीआर।',
      'स्वामित्व विलेखों एवं भारमुक्त प्रमाण पत्रों का स्वचालित एआई सत्यापन।',
      'उपग्रह इमेजरी के साथ कैडस्ट्रल नक्शों का सटीक स्थानिक भू-संरेखण।',
    ],
    pointsBn: [
      'জটিল গ্রাম্য হস্তলিখিত রাজस्व রেকর্ডের জন্য মাল্টিলিংগুয়াল নিউরাল OCR।',
      'স্বয়ংক্রিয় সিম্যান্টিক ভ্যালিডেশন ডিডসকে এনকাম্ব্রেন্স সার্টিফিকেটের সাথে ক্রস-চেক করে।',
      'জিও-রেক্টিফিকেশন স্যাটেলাইট ইমেজকে ভেক্টর ক্যাডাস্ট্রাল পার্সেলের সাথে এলাইন করে।',
    ],
    icon: 'Cpu',
    statusBadge: 'Intelligent Processing',
    statusBadgeHi: 'बौद्धिक प्रसंस्करण',
    statusBadgeBn: 'বুদ্ধিমান প্রসেসিং',
    color: 'sky',
  },
  {
    stepNumber: '03',
    title: 'Unified National Dashboard',
    titleHi: 'एकीकृत राष्ट्रीय डैशबोर्ड',
    titleBn: 'একীকৃত জাতীয় ড্যাশবোর্ড',
    tag: 'Seamless Governance',
    tagHi: 'पारदर्शी सुशासन',
    tagBn: 'সহজ শাসন ব্যবস্থা',
    points: [
      'Single pane of glass tracking acquisition lifecycle under RFCTLARR Act 2013.',
      'Automated Section 4, 11, 19 milestone clearances and real-time SLA alerts.',
      'Direct Benefit Transfer (DBT) via PFMS with Aadhaar-linked compensation disbursal.',
    ],
    pointsHi: [
      'भूमि अधिग्रहण अधिनियम 2013 के अंतर्गत प्रत्येक चरण की रीयल-टाइम निगरानी।',
      'धारा 4, 11 एवं 19 के वैधानिक क्लीयरेंस और स्वतः समयसीमा सूचनाएं।',
      'पीएफएमएस के माध्यम से प्रत्यक्ष लाभ अंतरण (डीबीटी) द्वारा पारदर्शी मुआवजा।',
    ],
    pointsBn: [
      'RFCTLARR আইন ২০১৩-এর অধীনে অর্জন লাইফসাইকেল ট্র্যাক করার জন্য সিঙ্গেল পেন অফ গ্লাস।',
      'স্বয়ংক্রিয় ধারা ৪, ১১, ১৯ মাইলস্টোন ক্লিয়ারেন্স এবং রিয়েল-টাইম SLA অ্যালার্ট।',
      'PFMS-এর মাধ্যমে ডায়রেক্ট বেনিফিট ট্রান্সফার (DBT) আধার-লিংকড কমপেনসেশন বিতরণের সাথে।',
    ],
    icon: 'LayoutDashboard',
    statusBadge: 'End-to-End Governance',
    statusBadgeHi: 'संपूर्ण पारदर्शी शासन',
    statusBadgeBn: 'এন্ড-টু-এন্ড গভর্নেন্স',
    color: 'emerald',
  },
];

export const KEY_MODULES: KeyModuleInfo[] = [
  {
    id: 'ai-extraction',
    title: 'AI Extraction & Validation',
    titleHi: 'एआई उद्धरण एवं सत्यापन',
    titleBn: 'এআই এক্সট্রাকশন ও ভ্যালিডেশন',
    tag: 'Vision & NLP Engine',
    tagHi: 'विजन एवं भाषा इंजन',
    tagBn: 'ভিশন এবং এনএলপি ইঞ্জিন',
    description: 'Automated extraction of Jamabandi, Khasra, Khatoni records with mutation anomaly detection.',
    descriptionHi: 'जमाबंदी, खसरा एवं खतौनी अभिलेखों का स्वतः निष्कर्षण तथा म्यूटेशन विसंगति पहचान।',
    descriptionBn: 'জমাবন্দি, খসরা, খতাউনি রেকর্ডের স্বয়ংক্রিয় এক্সট্রাকশন এবং মিউটেশন অসামঞ্জসylic ফলাফল।',
    details: [
      'Recognizes 14+ Indian Indic scripts (Hindi, Marathi, Telugu, Tamil, Bengali, etc.).',
      'Deep fraud detection checks against duplicate sale deeds and disputed mortgages.',
      'Extracts co-sharer equity fractions and automatically computes rightful share.',
    ],
    detailsHi: [
      '14 से अधिक भारतीय भाषाओं एवं लिपि प्रारूपों का समर्थन।',
      'दोहरे विक्रय विलेख एवं विवादित बंधक पर तत्काल अलर्ट।',
      'सह-खातेदारों के हिस्से का स्वचालित आनुपातिक विभाजन।',
    ],
    detailsBn: [
      '১৪টিরও বেশি ভারতীয় ভাষা ও লিপি ফরম্যাট সমর্থন করে।',
      'ডুপ্লিকেট সেল डीড এবং বিবাদিত মর্টগেজের বিরুদ্ধে গভীর ফ্রড সনাক্তকরণ।',
      'সহ-শেয়ারহোল্ডারের ইকুইটি ভগ্নাংশ বের করে স্বয়ংক্রিয়ভাবে অধিকার গণনা করে।',
    ],
    icon: 'FileSearch',
    sampleMetric: '99.4% Extraction F1',
    sampleMetricLabel: 'Accuracy on degraded paper records',
    sampleMetricLabelHi: 'जीर्ण अभिलेखों पर सटीकता दर',
    sampleMetricLabelBn: 'পুরনো কাগজি রেকর্ডে নির্ভুলতার হার',
  },
  {
    id: 'rbac-workflow',
    title: 'RBAC Workflow Engine',
    titleHi: 'भूमिका-आधारित कार्यप्रवाह इंजन',
    titleBn: 'আরবিএসি ওয়ার্কফ্লো ইঞ্জিন',
    tag: 'Statutory Compliance',
    tagHi: 'वैधानिक अनुपालन',
    tagBn: 'বিধানগত সুনির্দেশনা',
    description: 'Multi-tier approval hierarchy from Field Patwari to LAO, CALA, and District Collector.',
    descriptionHi: 'पटवारी, कानूनगो से लेकर एलएओ, सीएएलए एवं जिलाधिकारी तक बहु-स्तरीय अनुमोदन श्रृंखला।',
    descriptionBn: 'ফিল্ড পটোয়ারি থেকে এলএও, সিএএলএ এবং জেলা কালেক্টর পর্যন্ত মাল্টি-টিয়ার অনুমোদন শৃঙ্খল।',
    details: [
      'Adheres strictly to RFCTLARR Act 2013 statutory timelines and objection windows.',
      'Cryptographic tamper-evident audit logs secured on National NIC Cloud.',
      'Automated delegation of powers with digital signature (DSC) integration.',
    ],
    detailsHi: [
      'आरएफसीटीएलएआरआर अधिनियम 2013 की वैधानिक समय-सीमा का कड़ाई से पालन।',
      'क्रिप्टोग्राफिक डिजिटल हस्ताक्षर (डीएससी) द्वारा सुरक्षित ऑडिट लॉग।',
      'आपत्तियों के निवारण हेतु स्वतः कार्य आवंटन एवं सूचना प्रणाली।',
    ],
    detailsBn: [
      'আরএফসিটিএলএআরআর আইন ২০১৩-এর বৈधानিক সময়সীমা এবং আপত্তি উইন্ডোর সুনির্দিষ্ট অনুসরণ।',
      'জাতীয় এনআইসি ক্লাউডে সুরক্ষিত ক্রিপ্টোগ্রাফিক টেম্পার-ইভিডেন্ট অডিট লগ।',
      'ডিজিটাল স্বাক্ষর (ডিএসসি) אינ্টিগ্রেশন کے ساتھ 셀ফ-অটোমেটেডDelegation।',
    ],
    icon: 'ShieldCheck',
    sampleMetric: '42-Day Turnaround',
    sampleMetricLabel: 'Avg. Section 11 to 19 clearance',
    sampleMetricLabelHi: 'धारा 11 से 19 क्लीयरेंस औसत समय',
    sampleMetricLabelBn: 'ধারা ১১ থেকে ১৯ ক্লিয়ারেন্স গড় সময়',
  },
  {
    id: 'gis-spatial',
    title: 'GIS Spatial Visualization',
    titleHi: 'जीआईएस स्थानिक दृश्यीकरण',
    titleBn: 'জিআইএস স্পেশিয়াল ভিজ্যুয়ালাইজেশন',
    tag: 'Geospatial Intelligence',
    tagHi: 'भू-स्थानिक बुद्धिमत्ता',
    tagBn: 'জিওস্পেশিয়াল ইন্টেলিজেন্স',
    description: 'Satellite cadastre overlay, acquisition corridor boundary alignment, and parcel conflict heatmaps.',
    descriptionHi: 'उपग्रह कैडस्ट्रल ओवरले, अधिग्रहण गलियारा सीमा संरेखण एवं भूखंड विवाद हीटमैप।',
    descriptionBn: 'স্যাটেলাইট ক্যাডাস্ট্রাল ওভারলে, অর্জন করিডোর বাউন্ডারি এলাইনমেন্ট এবং পার্সেল দ্বন্দ্ব হিটম্যাপ।',
    details: [
      'Multi-layer high-resolution satellite imagery synchronized with Bhunaksha cadastre.',
      'Buffer zone conflict analyzer for linear infrastructure (Highways, Rail, Pipelines).',
      'Instant parcel measurement calculation down to square meters with geo-coordinates.',
    ],
    detailsHi: [
      'भू-नक्शा के साथ एकीकृत उच्च-रिज़ॉल्यूशन उपग्रह इमेजरी ओवरले।',
      'हाईवे, रेल एवं पाइपलाइन कॉरिडोर हेतु बफर ज़ोन प्रभाव विश्लेषण।',
      'अक्षांश-देशांतर निर्देशांकों सहित भूखंड का वर्ग मीटर में सटीक मापन।',
    ],
    detailsBn: [
      'ভূনকশার সাথে সিঙ্ক্রোনাইজড মাল্টি-লেয়ার হাই-রেজোলিউশন স্যাটেলাইট ইমেজারি।',
      'লিনিয়ার ইনফ্রাস্ট্রাকচারের (হাইওয়ে, রেল, পাইপলাইন) জন্য বাফার জোন কনফ্লিক্ট অ্যানালাইজার।',
      'জিও-কোঅর্ডিনেটসহ বর্গ মিটারে পার্সেল মাপের ইনস্ট্যান্ট ক্যালকুলেশন।',
    ],
    icon: 'MapPin',
    sampleMetric: '1.2m Accuracy',
    sampleMetricLabel: 'DGPS & Satellite vector alignment',
    sampleMetricLabelHi: 'डीजीपीएस एवं उपग्रह संरेखण परिशुद्धता',
    sampleMetricLabelBn: 'ডিজিপিএস এবং স্যাটেলাইট ভেক্টর এলাইনমেন্ট নির্ভুলতা',
  },
  {
    id: 'exec-dashboard',
    title: 'Executive Dashboards',
    titleHi: 'कार्यकारी डैशबोर्ड',
    titleBn: 'এগজিকিউটিভ ড্যাশবোর্ড',
    tag: 'Macro Decision Support',
    tagHi: 'नीतिगत निर्णय समर्थन',
    tagBn: 'ম্যাক্রো সিদ্ধান্ত সাপোর্ট',
    description: 'Real-time macro KPIs, bottleneck alerts, delay prediction, and fund utilization tracking.',
    descriptionHi: 'रीयल-टाइम राष्ट्रीय संकेतक, अवरोध अलर्ट, विलंब पूर्वानुमान एवं निधि उपयोग ट्रैकिंग।',
    descriptionBn: 'রিয়েল-টাইম ম্যাক্রো কেপিআই, বটলনেক অ্যালার্ট, ডिले প্রেডিকশন, এবং ফান্ড ইউটিলাইজেশন ট্র্যাকিং।',
    details: [
      'State-by-state heatmaps benchmarking project velocity and land clearance speed.',
      'Predictive AI forecasting litigation bottlenecks based on historical court records.',
      'Treasury & PFMS escrow ledger monitoring compensation balance in real time.',
    ],
    detailsHi: [
      'राज्यवार तुलनात्मक रैंकिंग एवं भूमि हस्तांतरण गति का विश्लेषण।',
      'पुराने न्यायिक मामलों के आधार पर संभावित विवादों का पूर्व-आकलन।',
      'पीएफएमएस के माध्यम से समर्पित मुआवजा निधि का पारदर्शी खाता।',
    ],
    detailsBn: [
      'রাজ্য-বARAM কর্ডার হিটম্যাপ বেঞ্চমার্কিং প্রজেক্ট ভেলোসিটি এবং ল্যান্ড ক্লিয়ারেন্স স্পিড।',
      'ঐতিহাসিক কোর্ট রেকর্ডের ভিত্তিতে প্রেডিক্টিভ এআই ফোরকাস্টিং লিটিগেশন বটলনেক।',
      'ট্রেজারি এবং পিএফএমএস এস্ক্রো লেজার রিয়েল-টাইমে কম্পেনসেশন ব্যালেন্স মনিটরিং।',
    ],
    icon: 'BarChart3',
    sampleMetric: '₹68,420+ Cr',
    sampleMetricLabel: 'PFMS disbursed funds tracked',
    sampleMetricLabelHi: 'पीएफएमएस द्वारा अंतरित निधि निगरानी',
    sampleMetricLabelBn: 'পিএফএমএস দ্বারা বিতরণকৃত ফান্ড ট্র্যাক করা',
  },
];

export const STAKEHOLDER_PERSONAS: PersonaInfo[] = [
  {
    id: 'pia',
    roleCode: 'PIA',
    title: 'Project Implementing Agency',
    titleHi: 'परियोजना क्रियान्वयन एजेंसी (पीआईए)',
    titleBn: 'প্রজেক্ট ইমপ্লিমেন্টিং এজেন্সি (পিআইএ)',
    subtitle: 'NHAI, Railways, Metro, Dedicated Freight Corridor',
    subtitleHi: 'एनएचएआई, भारतीय रेल, मेट्रो, डेडिकेटेड फ्रेट कॉरिडोर',
    subtitleBn: 'এনএইচএআই, ভারতীয় রেল, মেট্রো, ডেডিকেটেড ফ্রেট করিডোর',
    badge: 'Infrastructure Entity',
    badgeHi: 'बुनियादी ढांचा इकाई',
    badgeBn: 'ইনফ্রাস্ট্রাকচার এন্টিটি',
    description: 'Submits alignment proposals, uploads engineering CAD/GIS alignments, deposits acquisition funds, and tracks section-wise handovers.',
    descriptionHi: 'संरेखण प्रस्ताव प्रस्तुत करना, सीएडी/जीआईएस मानचित्र अपलोड करना, मुआवजा राशि जमा करना एवं हस्तांतरण ट्रैक करना।',
    descriptionBn: 'এলাইনমেন্ট প্রস্তাব জমা দেওয়া, ইঞ্জিনিয়ারিং CAD/GIS এলাইনমেন্ট আপলোড করা, অর্জন ফান্ড জমা করা এবং সেকশন-ভাইজ হ্যান্ডওভার ট্র্যাক করা।',
    keyResponsibilities: ['Corridor proposal filing', 'Fund deposit requisition', 'Handover clearance tracking'],
    keyResponsibilitiesHi: ['गलियारा प्रस्ताव प्रस्तुत करना', 'मुआवजा निधि जमा करना', 'भूमि हस्तांतरण की निगरानी'],
    keyResponsibilitiesBn: ['করিডোর প্রস্তাব ফাইল করা', 'ফান্ড ডিপোজিট অনুরোধ', 'হ্যান্ডওভার ক্লিয়ারেন্স ট্র্যাকিং'],
    primaryEntity: 'Central / State PSUs',
    primaryEntityHi: 'केंद्रीय / राज्य सार्वजनिक उपक्रम',
    primaryEntityBn: 'কেন্দ্রীয় / রাজ্য পিএসইউ',
    accentColor: 'indigo',
  },
  {
    id: 'field-officer',
    roleCode: 'FIELD',
    title: 'Field Officer & Surveyor',
    titleHi: 'क्षेत्रीय अधिकारी एवं अमीन/सर्वेयर',
    titleBn: 'ফিল্ড অফিসার ও সার্ভেয়র',
    subtitle: 'Patwari, Revenue Inspector, Kanungo, Amin',
    subtitleHi: 'पटवारी, कानूनगो, राजस्व निरीक्षक, अमीन',
    subtitleBn: 'পটোয়ারি, রেভ뉴 ইন্সপেক্টর, কানুঙ্গো, আমিন',
    badge: 'Ground Verification',
    badgeHi: 'भूमि सत्यापन',
    badgeBn: 'গ্রাউন্ড ভেরিফিকেশন',
    description: 'Performs Joint Measurement Surveys (JMS), uploads geo-tagged ground photos, tree/structure valuations, and boundary verification.',
    descriptionHi: 'संयुक्त माप सर्वेक्षण (जेएमएस), जियो-टैग ग्राउंड फोटो, वृक्ष/संरचना मूल्यांकन एवं सीमा का सत्यापन।',
    descriptionBn: 'যউন্ট মেজারমেন্ট সার্ভে (জেএমএস), জিও-ট্যাগ গ্রাউন্ড ফটো, বৃক্ষ/কাঠামো মুল্যায়ন এবং সীমানা যাচাইকরণ করে।',
    keyResponsibilities: ['Ground survey (JMS) input', 'Tree & asset count valuation', 'Dispute notation on-site'],
    keyResponsibilitiesHi: ['संयुक्त माप सर्वेक्षण दर्ज करना', 'परिसंपत्ति मूल्यांकन', 'स्थल पर विवाद दर्ज करना'],
    keyResponsibilitiesBn: ['গ্রাউন্ড সার্ভে (জেএমএস) ইনপুট', 'বৃক্ষ ও সম্পদ মুল্যায়ন', 'সাইটে বিবাদ নথিভুক্তি'],
    primaryEntity: 'Tehsil Revenue Cadre',
    primaryEntityHi: 'तहसील राजस्व संवर्ग',
    primaryEntityBn: 'তহসিল রেভ뉴 ক্যাডর',
    accentColor: 'teal',
  },
  {
    id: 'lao',
    roleCode: 'LAO',
    title: 'Desk Validator / LAO',
    titleHi: 'डेस्क सत्यापनकर्ता / एलएओ',
    titleBn: 'ডেস্ক ভ্যালিডেটর / এলএও',
    subtitle: 'Land Acquisition Officer & Revenue Tehsildar',
    subtitleHi: 'भूमि अधिग्रहण अधिकारी एवं राजस्व तहसीलदार',
    subtitleBn: 'ল্যান্ড অকুইজিশন অফিসার এবং রেভ뉴 তহসিলদার',
    badge: 'Statutory Scrutiny',
    badgeHi: 'वैधानिक संवीक्षा',
    badgeBn: 'বিধানগত সমালোচনা',
    description: 'Scrutinizes Khasra ownership chains, examines public objections under Section 15, drafts Preliminary Awards, and verifies encumbrances.',
    descriptionHi: 'खसरा स्वामित्व श्रृंखला की संवीक्षा, धारा 15 के तहत जनता की आपत्तियों की सुनवाई एवं प्रारंभिक पंचाट तैयार करना।',
    descriptionBn: 'খসরা সোঁইয়েত্ব শৃঙ্খলা তদন্ত, ধারা ১৫-এর অধীনে পাবলিক আপত্তি শোনা এবং প্রিলিমিনারি অওয়ার্ড ড্রাফট করা।',
    keyResponsibilities: ['Section 15 objection hearing', 'Market value matrix calculation', 'Draft award preparation'],
    keyResponsibilitiesHi: ['धारा 15 आपत्ति सुनवाई', 'सर्कल रेट/बाजार मूल्य गणना', 'प्रारूप पंचाट निर्माण'],
    keyResponsibilitiesBn: ['ধারা ১৫ আপত্তি শোনা', 'মার্কেট ভ্যালু ম্যাট্রিক্স ক্যালকুলেশন', 'ড্রাফট অওয়ার্ড প্রস্তুতকরণ'],
    primaryEntity: 'District Revenue Office',
    primaryEntityHi: 'जिला राजस्व कार्यालय',
    primaryEntityBn: 'জেলা রেভ뉴 অফিস',
    accentColor: 'blue',
  },
  {
    id: 'approver',
    roleCode: 'CALA/DM',
    title: 'Approver / CALA & DM',
    titleHi: 'अनुमोदनकर्ता / सीएएलए एवं डीएम',
    titleBn: 'অনুমোদনকারী / সিএএলএ এবং ডিএম',
    subtitle: 'Competent Authority Land Acquisition & District Magistrate',
    subtitleHi: 'सक्षम प्राधिकारी (भूमि अधिग्रहण) एवं जिला कलेक्टर',
    subtitleBn: 'সক্ষম প্রাধিকার (ভূমি অর্জন) এবং জেলা মেজিস্ট্রেট',
    badge: 'Sanctioning Authority',
    badgeHi: 'स्वीकृति प्राधिकारी',
    badgeBn: 'অনুমোদনকারী প্রাধিকার',
    description: 'Final statutory sanction under Section 19 declaration, approves the final compensation award under Section 23/30, and authorizes DBT release.',
    descriptionHi: 'धारा 19 घोषणा को अंतिम स्वीकृति, धारा 23/30 के अंतर्गत अंतिम मुआवजा पंचाट अनुमोदन एवं डीबीटी भुगतान जारी करने का आदेश।',
    descriptionBn: 'ধারা ১৯ ঘোষণার অধীনে চূড়ান্ত বৈধানিক অনুমোদন, ধারা ২৩/৩০-এর অধীনে চূড়ান্ত ক্ষতিপূরণ অওয়ার্ড অনুমোদন এবং DBT রিলিজ অনুমোদন।',
    keyResponsibilities: ['Section 19 statutory signoff', 'Final award sanction', 'PFMS compensation release order'],
    keyResponsibilitiesHi: ['धारा 19 वैधानिक हस्ताक्षर', 'अंतिम पंचाट स्वीकृति', 'पीएफएमएस मुआवजा जारी आदेश'],
    keyResponsibilitiesBn: ['ধারা ১৯ বৈধানিক সাইন-অফ', 'চূড়ান্ত অওয়ার্ড অনুমোদন', 'পিএফএমএস কমপেনসেশন রিলিজ অর্ডার'],
    primaryEntity: 'District Administration',
    primaryEntityHi: 'जिला प्रशासन',
    primaryEntityBn: 'জেলা প্রশাসন',
    accentColor: 'emerald',
  },
  {
    id: 'executive',
    roleCode: 'EXEC',
    title: 'Executive & Policy Maker',
    titleHi: 'कार्यकारी एवं नीति निर्माता',
    titleBn: 'এগজিকিউটিভ ও পলিসি মেকার',
    subtitle: 'Ministry of Rural Development, Chief Secretaries, NITI Aayog',
    subtitleHi: 'ग्रामीण विकास मंत्रालय, मुख्य सचिव, नीति आयोग',
    subtitleBn: 'গ্রামীন উন্নয়ন মন্ত্রণালয়, মুখ্য সচিব, নিটি আयोग',
    badge: 'National Oversight',
    badgeHi: 'राष्ट्रीय पर्यवेक्षण',
    badgeBn: 'জাতীয় নির্দেশনা',
    description: 'Monitors PM-GatiShakti corridor alignments, national fund disbursement velocity, inter-state land acquisition bottlenecks, and policy levers.',
    descriptionHi: 'पीएम-गतिशक्ति गलियारा परियोजनाओं, राष्ट्रीय स्तर पर मुआवजा वितरण एवं अंतर-राज्यीय नीतिगत समन्वय की समीक्षा।',
    descriptionBn: 'পিএম-গতিশক্তি করিডোর এলাইনমেন্ট, জাতীয় ফান্ড বিতরণ ভেলোসিটি, আন্তঃরাজ্যীয় ভূমি অর্জন বটলনেক এবং পলিসি লিভার মনিটর করে।',
    keyResponsibilities: ['PM-GatiShakti alignment oversight', 'State progress benchmarking', 'Inter-ministerial resolution'],
    keyResponsibilitiesHi: ['गतिशक्ति परियोजना निगरानी', 'राज्य प्रगति समीक्षा', 'अंतर-मंत्रालयी समन्वय'],
    keyResponsibilitiesBn: ['পিএম-গতিশক্তি এলাইনমেন্ট ওভারসাইট', 'রাজ্য প্রগতি বেঞ্চমার্কিং', 'ইন্টার-মিনিস্টেরিয়াল রেজোলিউশন'],
    primaryEntity: 'Union & State Leadership',
    primaryEntityHi: 'केंद्रीय एवं राज्य नेतृत्व',
    primaryEntityBn: 'কেন্দ্রীয় ও রাজ্য নেতৃত্ব',
    accentColor: 'purple',
  },
  {
    id: 'citizen',
    roleCode: 'CITIZEN',
    title: 'Citizen & Landowner',
    titleHi: 'नागरिक एवं भू-स्वामी',
    titleBn: 'নাগরিক ও ভূমালিক',
    subtitle: 'Landowner, Farmer, Legal Heir, Affected Family',
    subtitleHi: 'जमीन मालिक, किसान, विधिक उत्तराधिकारी, प्रभावित परिवार',
    subtitleBn: 'জমির মালিক, কৃষক, قانونی উত্তরাধিকারী, প্রভাবিত পরিবার',
    badge: 'Public Transparency',
    badgeHi: 'जन पारदर्शिता',
    badgeBn: 'পাবলিক ট্রান্সপারেন্সি',
    description: 'Tracks notified land parcel in real-time, submits online objections/claims, views compensation award calculations, and tracks direct DBT credit.',
    descriptionHi: 'अधिग्रहीत जमीन की स्थिति रीयल-टाइम देखना, ऑनलाइन आपत्ति दर्ज करना, मुआवजे की गणना देखना एवं खाते में डीबीटी भुगतान ट्रैक करना।',
    descriptionBn: 'রিয়েল-টাইমে বিজ্ঞপ্তিpty ভূমি পার্সেল ট্র্যাক করা, অনলাইন আপত্তি/দাবি জমা দেওয়া, ক্ষতিপূরণ অওয়ার্ড গণনা দেখা এবং সরাসরি DBT ক্রেডিট ট্র্যাক করা।',
    keyResponsibilities: ['Khasra status inquiry', 'E-objection / Claim submission', 'PFMS bank credit tracking'],
    keyResponsibilitiesHi: ['खसरा स्थिति खोज', 'ई-आपत्ति/दावा प्रस्तुति', 'बैंक खाते में मुआवजा ट्रैकिंग'],
    keyResponsibilitiesBn: ['খসরা স্ট্যাটাস إنكুইরি', 'ই-আপত্তি / দাবি সাবমিশন', 'পিএফএমএস ব্যাংক ক্রেডিট ট্র্যাকিং'],
    primaryEntity: 'General Public of India',
    primaryEntityHi: 'भारत का सामान्य नागरिक',
    primaryEntityBn: 'ভারতের সাধারণ জনগণ',
    accentColor: 'amber',
  },
  {
    id: 'admin',
    roleCode: 'ADMIN',
    title: 'System Administrator',
    titleHi: 'सिस्टम प्रशासक / नोडल अधिकारी',
    titleBn: 'সিস্টেম অ্যাডমিনিস্ট্রেটর',
    subtitle: 'NIC Nodal Officers, CERT-In Auditors, State Registry Admins',
    subtitleHi: 'एनआईसी नोडल अधिकारी, सीईआरटी-इन ऑडिटर, राज्य रजिस्ट्री एडमिन',
    subtitleBn: 'এনআইসি নোডাল অফিসার, সার্ট-ইন অডিটর, স্টেট রেজিস্ট্রি অ্যাডমিন',
    badge: 'Security & Integrity',
    badgeHi: 'सुरक्षा एवं अखंडता',
    badgeBn: 'সিকিউরিটি অ্যান্ড ইন্টিগ্রিটি',
    description: 'Manages user credentials via Parichay/MeriPehchan, audits cryptographic access logs, configures state circle rates, and oversees API uptime.',
    descriptionHi: 'परिचय/मेरीपहचान एसएसओ प्रबंधन, क्रिप्टोग्राफिक ऑडिट लॉग की जांच, राज्य सर्किल दरों का विन्यास एवं सुरक्षा निरीक्षण।',
    descriptionBn: 'পরিচয়/মেরি পেহচান এর মাধ্যমে ইউজার ক্রেডেনশিয়াল পরিচালনা, ক্রিপ্টোগ্রাফিক অ্যাক্সেস লগ অডিট, স্টেট সার্কেল রেট কনফিগার এবং API আপটাইম ওভারসাইট।',
    keyResponsibilities: ['SSO & Parichay role provisioning', 'Audit log tamper monitoring', 'State registry API sync'],
    keyResponsibilitiesHi: ['एसएसओ परिचय भूमिका प्रबंधन', 'ऑडिट लॉग सुरक्षा जांच', 'एपीआई डेटा समन्वय'],
    keyResponsibilitiesBn: ['SSO এবং পরিচয় রোল প্রভিশনিং', 'অডিট লগ টেম্পার মনিটরিং', 'স্টেট রেজিস্ট্রি API সিঙ্ক'],
    primaryEntity: 'NIC / MeitY / State DILRMP',
    primaryEntityHi: 'एनआईसी / इलेक्ट्रॉनिकी मंत्रालय',
    primaryEntityBn: 'এনআইসি / মাইটি / স্টেট ডিআইএলআরএমপি',
    accentColor: 'slate',
  },
];

export const TRANSPARENCY_KPIS = [
  {
    id: 'area-notified',
    value: '4,82,590+',
    unit: 'Hectares',
    unitHi: 'हेक्टेयर',
    unitBn: 'হেক্টেয়ার',
    label: 'Area Notified for National Projects',
    labelHi: 'राष्ट्रीय परियोजनाओं हेतु अधिसूचित क्षेत्रफल',
    labelBn: 'জাতীয় প্রজেক্টের জন্য বিজ্ঞপ্তি করা এলাকা',
    subtext: 'Across 1,240+ linear corridors and economic zones',
    subtextHi: '1,240+ राष्ट्रीय राजमार्ग, रेलवे एवं आर्थिक गलियारों में',
    subtextBn: '১,২৪০+ লিনিয়ার করিডোর এবং অর্থনৈতিক অঞ্চলে',
    color: 'amber',
  },
  {
    id: 'comp-disbursed',
    value: '₹68,420+ Cr',
    unit: 'Direct PFMS / DBT',
    unitHi: 'प्रत्यक्ष पीएफएमएस / डीबीटी',
    unitBn: 'প্রত্যক্ষ পিএফএমএস / ডিবিটি',
    label: 'Compensation Disbursed Directly',
    labelHi: 'प्रत्यक्ष बैंक खातों में अंतरित कुल मुआवजा',
    labelBn: 'সরাসরি ব্যাংক অ্যাকাউন্টে বিতরণকৃত মোট ক্ষতিপূরণ',
    subtext: 'Zero intermediaries; 100% Aadhaar-seeded transparent payout',
    subtextHi: 'शून्य बिचौलिया; 100% आधार से जुड़े बैंक खातों में',
    subtextBn: 'শূন্য মধ্যস্থ; ১০০% আধার-সিডেড পayout',
    color: 'emerald',
  },
  {
    id: 'cases-resolved',
    value: '1,42,830+',
    unit: 'Parcels Awarded',
    unitHi: 'भूखंड पंचाट पूर्ण',
    unitBn: 'পার্সেল অওয়ার্ড সম্পন্ন',
    label: 'Acquisition Cases Resolved',
    labelHi: 'निस्तारित भूमि अधिग्रहण प्रकरण',
    labelBn: 'নিষ্পত্তಿ অর্জন কেসসমূহ',
    subtext: '92% reduction in Section 15 objections turnaround time',
    subtextHi: 'धारा 15 आपत्तियों के निस्तारण समय में 92% की कमी',
    subtextBn: 'ধারা ১৫ আপত্তির টার্নআরাউন্ড টাইমে ৯২% কমানো',
    color: 'sky',
  },
  {
    id: 'sync-rate',
    value: '94.8%',
    unit: 'Cadastral Sync',
    unitHi: 'भू-नक्शा समन्वय',
    unitBn: 'ক্যাডাস্ট্রাল সিঙ্ক',
    label: 'Records Digitized & Geo-Referenced',
    labelHi: 'डिजिटलीकृत एवं भू-संदर्भित भू-अभিলेख',
    labelBn: 'ডিজিটাইজড ও জিও-রেফারেন্সড রেকর্ড',
    subtext: 'Synchronized with Bhunaksha and State Land Registries',
    subtextHi: 'भू-नक्शा एवं राज्य भू-अभिलेखों के साथ लाइव सिंक',
    subtextBn: 'ভূনকশা এবং রাজ্য ভূমি রেজিস্ট্রির সাথে সিঙ্ক্রোনাইজড',
    color: 'indigo',
  },
];

export const SAMPLE_LAND_RECORDS: LandRecordStatus[] = [
  {
    notificationId: 'LA-UP-GBN-2025-0842',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    village: 'Dayanatpur',
    khasraNo: '142/2',
    landownerName: 'Shri Ramswaroop Singh & Smt. Kanti Devi',
    projectAffiliation: 'Noida International Airport (Jewar) Phase II Infrastructure Corridor',
    notifiedAreaHectares: 0.842,
    currentStage: 'Award Inquiry',
    stageIndex: 4,
    compensationCalculated: '₹1,48,60,000',
    solatiumComponent: '₹74,30,000 (100% Solatium included under RFCTLARR Act 2013)',
    dbtPaymentStatus: 'Sanction Order Issued',
    utrReference: 'PFMS-RBI-20250914-99841',
    dateNotified: '14 Jan 2025',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-MH-PUN-2024-1920',
    state: 'Maharashtra',
    district: 'Pune',
    tehsil: 'Haveli',
    village: 'Wagholi',
    khasraNo: '88/A/1',
    landownerName: 'Shri Dnyaneshwar Babanrao Patil',
    projectAffiliation: 'Pune Outer Ring Road Expressway Project - Section 3',
    notifiedAreaHectares: 0.45,
    currentStage: 'Compensation Disbursed',
    stageIndex: 5,
    compensationCalculated: '₹92,40,000',
    solatiumComponent: '₹46,20,000 (100% Solatium & 12% Interest)',
    dbtPaymentStatus: 'Processed via PFMS',
    utrReference: 'PFMS-SBI-20250811-44781',
    dateNotified: '02 Nov 2024',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-HR-SNP-2025-0311',
    state: 'Haryana',
    district: 'Sonipat',
    tehsil: 'Ganaur',
    village: 'Shahpur Turk',
    khasraNo: '412',
    landownerName: 'Shri Virender Kumar & Bros.',
    projectAffiliation: 'Western Dedicated Freight Corridor (WDFC) Yard Expansion',
    notifiedAreaHectares: 1.12,
    currentStage: 'Joint Measurement Survey',
    stageIndex: 2,
    compensationCalculated: '₹2,10,00,000 (Estimated)',
    solatiumComponent: 'Calculated post-JMS final verification',
    dbtPaymentStatus: 'Under Bank Verification',
    utrReference: 'PENDING_SANCTION',
    dateNotified: '28 Feb 2025',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-KA-BLR-2025-0774',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    tehsil: 'Hosakote',
    village: 'Sulibele',
    khasraNo: '29/3',
    landownerName: 'Smt. Lakshmi Venkataramanappa',
    projectAffiliation: 'Bengaluru-Chennai Expressway (NE-7) Link Road',
    notifiedAreaHectares: 0.38,
    currentStage: 'Sec 19 Declaration',
    stageIndex: 3,
    compensationCalculated: '₹84,50,000',
    solatiumComponent: 'RFCTLARR Schedule I Verified',
    dbtPaymentStatus: 'Sanction Order Issued',
    utrReference: 'PFMS-CAN-20250629-10924',
    dateNotified: '10 May 2025',
    disputeFlag: false,
  }
];

export const TICKER_NOTICES = [
  { text: 'Gazette: RFCTLARR Act Section 11(1) notification published for Delhi-Amritsar-Katra Expressway Package 4', textHi: 'राजपत्र: दिल्ली-अमृतसर-कटरा एक्सप्रेसवे पैकेज 4 हेतु धारा 11(1) अधिसूचना जारी', textBn: 'গেজেট: দিল্লি-অমৃতসর-কাটরা এক্সপ্রেসওয়ে প্যাকেজ ৪ এর জন্য ধারা ১১(১) বিজ্ঞপ্তি প্রকাশিত' },
  { text: 'Digital India Land Records: 28 States successfully onboarded on ZameenAI Unified RoR Grid', textHi: 'डिजिटल इंडिया भूमि अभिलेख: 28 राज्य ज़मीन एआई एकीकृत आरओआর ग्रিড पर सफलतापूर्वक जुड़े', textBn: 'ডিজিটাল ইন্ডিয়া ভূমি রেকর্ড: ২৮টি রাজ্য জামিন এআই ইউনিফাইড আরওআর গ্রিডে সফলভাবে যুক্ত' },
  { text: 'PFMS Direct Disbursal: Over ₹68,000 Crore credited directly to verified Aadhaar-linked farmer accounts', textHi: 'पीएफएमएस प्रत्यक्ष अंतरण: 68,000 करोड़ रुपये से अधिक सीधे किसानों के बैंक खातों में अंतरित', textBn: 'পিএফএমএস ডাইরেক্ট বিতরণ: ৬৮,০০০ কোটি টাকার বেশি যাচাইকৃত আধার-লিংক्ड কৃষক অ্যাকাউন্টে সরাসরি জমা' },
  { text: 'DILRMP Advisory: Drone-assisted aerial LiDAR survey completed for 1,200 km railway freight alignment', textHi: 'डीआईएलआरएमपी परामर्श: 1,200 किमी रेल कॉरिडोर हेतु ड्रोन-आधारित लिडार सर्वेक्षण संपन्न', textBn: 'ডিআইএলআরএমপি পরামর্শ: ১,২০০ কিমি রেল ফ্রেট অ্যালাইনমেন্টের জন্য ড্রোন-সহায়তা প্রাপ্ত অ되었으며 লিডার সার্ভে সম্পন্ন' },
];
