import { PersonaInfo, KeyModuleInfo, ProblemSolutionStep, LandRecordStatus } from './types';

export const HERO_CONTENT = {
  tagline: {
    en: 'Bringing Clarity to Land Acquisition and Records',
    hi: 'भूमि अधिग्रहण एवं अभिलेखों में पारदर्शिता और स्पष्टता',
  },
  missionStatement: {
    en: 'A unified, AI-driven platform for end-to-end land acquisition monitoring and intelligent land-record digitization',
    hi: 'संपूर्ण भूमि अधिग्रहण निगरानी एवं बौद्धिक भू-अभिलेख डिजिटलीकरण हेतु एक एकीकृत, एआई-संचालित राष्ट्रीय मंच',
  },
  officialCta: {
    en: 'Official Login',
    hi: 'अधिकारी लॉगिन',
  },
  officialCtaSub: {
    en: 'For PIAs, LAOs, CALA & District Magistrates',
    hi: 'पीआईए, एलएओ, सीएएलए एवं जिलाधिकारियों हेतु',
  },
  citizenCta: {
    en: 'Start Uploading',
    hi: 'शुरू करें अपलोडिंग',
  },
  citizenCtaSub: {
    en: 'Instant Khasra & Compensation Tracker',
    hi: 'खसरा एवं मुआवजा प्रत्यक्ष ट्रैकर',
  },
};

export const TRUST_PARTNERS = [
  {
    name: 'DILRMP 2.0',
    title: 'Digital India Land Records Modernization',
    titleHi: 'डिजिटल इंडिया भूमि अभिलेख आधुनिकीकरण कार्यक्रम',
    badge: 'National Program',
    badgeHi: 'राष्ट्रीय कार्यक्रम',
    type: 'Core Framework',
  },
  {
    name: 'LRMS Integration',
    title: 'Unified State Land Records Management System',
    titleHi: 'एकीकृत राज्य भू-अभिलेख प्रबंधन प्रणाली',
    badge: '28 States Synced',
    badgeHi: '28 राज्य एकीकृत',
    type: 'API Gateway',
  },
  {
    name: 'Ministry of Rural Development',
    title: 'Department of Land Resources (DoLR)',
    titleHi: 'ग्रामीण विकास मंत्रालय (भूमि संसाधन विभाग)',
    badge: 'Nodal Ministry',
    badgeHi: 'नोडल मंत्रालय',
    type: 'Governance',
  },
  {
    name: 'NIC Cloud MeghRaj',
    title: 'National Informatics Centre Infrastructure',
    titleHi: 'राष्ट्रीय सूचना विज्ञान केंद्र (एनआईसी)',
    badge: 'Tier-IV Secure',
    badgeHi: 'टियर-4 सुरक्षित',
    type: 'Secure Cloud',
  },
  {
    name: 'Bhunaksha & GIS Sync',
    title: 'Survey of India & Cadastral Mapping Grid',
    titleHi: 'भू-नक्शा एवं स्थानिक भू-मानचित्रण ग्रिड',
    badge: 'Spatial Engine',
    badgeHi: 'स्थानिक इंजन',
    type: 'GIS Registry',
  },
];

export const PROBLEM_SOLUTION_STEPS: ProblemSolutionStep[] = [
  {
    stepNumber: '01',
    title: 'Fragmented Records',
    titleHi: 'अव्यवस्थित एवं खंडित अभिलेख',
    tag: 'Legacy Challenge',
    tagHi: 'पारंपरिक समस्या',
    points: [
      'Disparate paper RoRs across states (Jamabandi, Khatoni, 7/12, Patta).',
      'Un-reconciled boundary demarcations leading to prolonged civil litigation.',
      'Manual, opaque compensation calculation causing citizen distrust.',
    ],
    pointsHi: [
      'विभिन्न राज्यों में अलग-अलग प्रारूप (जमाबंदी, खतौनी, 7/12, पट्टा)।',
      'अस्पष्ट सीमांकन जिससे वर्षों तक कानूनी विवाद एवं परियोजना विलंब।',
      'मैन्युअल और अपारदर्शी मुआवजा गणना प्रणाली।',
    ],
    icon: 'Layers',
    statusBadge: 'Legacy Burden',
    statusBadgeHi: 'पारंपरिक बाधा',
    color: 'amber',
  },
  {
    stepNumber: '02',
    title: 'AI Digitization & OCR',
    titleHi: 'एआई डिजिटलीकरण एवं ओसीआर',
    tag: 'ZameenAI Core Engine',
    tagHi: 'ज़मीन एआई मुख्य इंजन',
    points: [
      'Multilingual neural OCR for complex vernacular handwritten revenue records.',
      'Automated semantic validation cross-checking deeds against encumbrance certificates.',
      'Geo-rectification aligning satellite imagery with vector cadastral parcels.',
    ],
    pointsHi: [
      'हस्तलिखित क्षेत्रीय राजस्व अभिलेखों हेतु बहुभाषी न्यूरल ओसीआर।',
      'स्वामित्व विलेखों एवं भारमुक्त प्रमाण पत्रों का स्वचालित एआई सत्यापन।',
      'उपग्रह इमेजरी के साथ कैडस्ट्रल नक्शों का सटीक स्थानिक भू-संरेखण।',
    ],
    icon: 'Cpu',
    statusBadge: 'Intelligent Processing',
    statusBadgeHi: 'बौद्धिक प्रसंस्करण',
    color: 'sky',
  },
  {
    stepNumber: '03',
    title: 'Unified National Dashboard',
    titleHi: 'एकीकृत राष्ट्रीय डैशबोर्ड',
    tag: 'Seamless Governance',
    tagHi: 'पारदर्शी सुशासन',
    points: [
      'Single pane of glass tracking acquisition lifecycle under RFCTLARR Act 2013.',
      'Automated Section 4, 11, 19 milestone clearances and real-time SLA alerts.',
      'Direct Benefit Transfer (DBT) via PFMS with Aadhaar-linked compensation disbursal.',
    ],
    pointsHi: [
      'भूमि अधिग्रहण अधिनियम 2013 के अंतर्गत प्रत्येक चरण की रीयल-टाइम निगरानी।',
      'धारा 4, 11 एवं 19 के वैधानिक क्लीयरेंस और स्वतः समयसीमा सूचनाएं।',
      'पीएफएमएस के माध्यम से प्रत्यक्ष लाभ अंतरण (डीबीटी) द्वारा पारदर्शी मुआवजा।',
    ],
    icon: 'LayoutDashboard',
    statusBadge: 'End-to-End Governance',
    statusBadgeHi: 'संपूर्ण पारदर्शी शासन',
    color: 'emerald',
  },
];

export const KEY_MODULES: KeyModuleInfo[] = [
  {
    id: 'ai-extraction',
    title: 'AI Extraction & Validation',
    titleHi: 'एआई उद्धरण एवं सत्यापन',
    tag: 'Vision & NLP Engine',
    tagHi: 'विजन एवं भाषा इंजन',
    description: 'Automated extraction of Jamabandi, Khasra, Khatoni records with mutation anomaly detection.',
    descriptionHi: 'जमाबंदी, खसरा एवं खतौनी अभिलेखों का स्वतः निष्कर्षण तथा म्यूटेशन विसंगति पहचान।',
    details: [
      'Recognizes 14+ Indian Indic scripts (Hindi, Marathi, Telugu, Tamil, Bengali, etc.).',
      'Deep fraud detection checks against duplicate sale deeds and disputed mortgages.',
      'Extracts co-sharer equity fractions and automatically computes rightful share.',
    ],
    detailsHi: [
      '14 से अधिक भारतीय भाषाओं एवं लिपि प्रारूपों का समर्थन।',
      'दोहरे विक्रय विलेख एवं विवादित बंधक पर तत्काल अलर्ट।',
      'सह-खातेदारों के हिस्से का स्वचालित आनुपातिक विभाजन।',
    ],
    icon: 'FileSearch',
    sampleMetric: '99.4% Extraction F1',
    sampleMetricLabel: 'Accuracy on degraded paper records',
    sampleMetricLabelHi: 'जीर्ण अभिलेखों पर सटीकता दर',
  },
  {
    id: 'rbac-workflow',
    title: 'RBAC Workflow Engine',
    titleHi: 'भूमिका-आधारित कार्यप्रवाह इंजन',
    tag: 'Statutory Compliance',
    tagHi: 'वैधानिक अनुपालन',
    description: 'Multi-tier approval hierarchy from Field Patwari to LAO, CALA, and District Collector.',
    descriptionHi: 'पटवारी, कानूनगो से लेकर एलएओ, सीएएलए एवं जिलाधिकारी तक बहु-स्तरीय अनुमोदन श्रृंखला।',
    details: [
      'Adheres strictly to RFCTLARR Act 2013 statutory timelines and objection windows.',
      'Cryptographic tamper-evident audit logs secured on National NIC Cloud.',
      'Automated delegation of powers with digital signature (DSC) integration.',
    ],
    detailsHi: [
      'आरएफसीटीएलएआरआर अधिनियम 2013 की वैधानिक समय-सीमा का कड़ाई से पालन।',
      'क्रिप्टोग्राफिक डिजिटल हस्ताक्षर (डीएससी) द्वारा सुरक्षित ऑडिट लॉग।',
      'आपत्तियों के निवारण हेतु स्वतः कार्य आवंटन एवं सूचना प्रणाली।',
    ],
    icon: 'ShieldCheck',
    sampleMetric: '42-Day Turnaround',
    sampleMetricLabel: 'Avg. Section 11 to 19 clearance',
    sampleMetricLabelHi: 'धारा 11 से 19 क्लीयरेंस औसत समय',
  },
  {
    id: 'gis-spatial',
    title: 'GIS Spatial Visualization',
    titleHi: 'जीआईएस स्थानिक दृश्यीकरण',
    tag: 'Geospatial Intelligence',
    tagHi: 'भू-स्थानिक बुद्धिमत्ता',
    description: 'Satellite cadastre overlay, acquisition corridor boundary alignment, and parcel conflict heatmaps.',
    descriptionHi: 'उपग्रह कैडस्ट्रल ओवरले, अधिग्रहण गलियारा सीमा संरेखण एवं भूखंड विवाद हीटमैप।',
    details: [
      'Multi-layer high-resolution satellite imagery synchronized with Bhunaksha cadastre.',
      'Buffer zone conflict analyzer for linear infrastructure (Highways, Rail, Pipelines).',
      'Instant parcel measurement calculation down to square meters with geo-coordinates.',
    ],
    detailsHi: [
      'भू-नक्शा के साथ एकीकृत उच्च-रिज़ॉल्यूशन उपग्रह इमेजरी ओवरले।',
      'हाईवे, रेल एवं पाइपलाइन कॉरिडोर हेतु बफर ज़ोन प्रभाव विश्लेषण।',
      'अक्षांश-देशांतर निर्देशांकों सहित भूखंड का वर्ग मीटर में सटीक मापन।',
    ],
    icon: 'MapPin',
    sampleMetric: '1.2m Accuracy',
    sampleMetricLabel: 'DGPS & Satellite vector alignment',
    sampleMetricLabelHi: 'डीजीपीएस एवं उपग्रह संरेखण परिशुद्धता',
  },
  {
    id: 'exec-dashboard',
    title: 'Executive Dashboards',
    titleHi: 'कार्यकारी डैशबोर्ड',
    tag: 'Macro Decision Support',
    tagHi: 'नीतिगत निर्णय समर्थन',
    description: 'Real-time macro KPIs, bottleneck alerts, delay prediction, and fund utilization tracking.',
    descriptionHi: 'रीयल-टाइम राष्ट्रीय संकेतक, अवरोध अलर्ट, विलंब पूर्वानुमान एवं निधि उपयोग ट्रैकिंग।',
    details: [
      'State-by-state heatmaps benchmarking project velocity and land clearance speed.',
      'Predictive AI forecasting litigation bottlenecks based on historical court records.',
      'Treasury & PFMS escrow ledger monitoring compensation balance in real time.',
    ],
    detailsHi: [
      'राज्यवार तुलनात्मक रैंकिंग एवं भूमि हस्तांतरण गति का विश्लेषण।',
      'पुराने न्यायिक मामलों के आधार पर संभावित विवादों का पूर्व-आकलन।',
      'पीएफएमएस के माध्यम से समर्पित मुआवजा निधि का पारदर्शी खाता।',
    ],
    icon: 'BarChart3',
    sampleMetric: '₹68,420+ Cr',
    sampleMetricLabel: 'PFMS disbursed funds tracked',
    sampleMetricLabelHi: 'पीएफएमएस द्वारा अंतरित निधि निगरानी',
  },
];

export const STAKEHOLDER_PERSONAS: PersonaInfo[] = [
  {
    id: 'pia',
    roleCode: 'PIA',
    title: 'Project Implementing Agency',
    titleHi: 'परियोजना क्रियान्वयन एजेंसी (पीआईए)',
    subtitle: 'NHAI, Railways, Metro, Dedicated Freight Corridor',
    subtitleHi: 'एनएचएआई, भारतीय रेल, मेट्रो, डेडिकेटेड फ्रेट कॉरिडोर',
    badge: 'Infrastructure Entity',
    badgeHi: 'बुनियादी ढांचा इकाई',
    description: 'Submits alignment proposals, uploads engineering CAD/GIS alignments, deposits acquisition funds, and tracks section-wise handovers.',
    descriptionHi: 'संरेखण प्रस्ताव प्रस्तुत करना, सीएडी/जीआईएस मानचित्र अपलोड करना, मुआवजा राशि जमा करना एवं हस्तांतरण ट्रैक करना।',
    keyResponsibilities: ['Corridor proposal filing', 'Fund deposit requisition', 'Handover clearance tracking'],
    keyResponsibilitiesHi: ['गलियारा प्रस्ताव प्रस्तुत करना', 'मुआवजा निधि जमा करना', 'भूमि हस्तांतरण की निगरानी'],
    primaryEntity: 'Central / State PSUs',
    primaryEntityHi: 'केंद्रीय / राज्य सार्वजनिक उपक्रम',
    accentColor: 'indigo',
  },
  {
    id: 'field-officer',
    roleCode: 'FIELD',
    title: 'Field Officer & Surveyor',
    titleHi: 'क्षेत्रीय अधिकारी एवं अमीन/सर्वेयर',
    subtitle: 'Patwari, Revenue Inspector, Kanungo, Amin',
    subtitleHi: 'पटवारी, कानूनगो, राजस्व निरीक्षक, अमीन',
    badge: 'Ground Verification',
    badgeHi: 'भूमि सत्यापन',
    description: 'Performs Joint Measurement Surveys (JMS), uploads geo-tagged ground photos, tree/structure valuations, and boundary verification.',
    descriptionHi: 'संयुक्त माप सर्वेक्षण (जेएमएस), जियो-टैग ग्राउंड फोटो, वृक्ष/संरचना मूल्यांकन एवं सीमा का सत्यापन।',
    keyResponsibilities: ['Ground survey (JMS) input', 'Tree & asset count valuation', 'Dispute notation on-site'],
    keyResponsibilitiesHi: ['संयुक्त माप सर्वेक्षण दर्ज करना', 'परिसंपत्ति मूल्यांकन', 'स्थल पर विवाद दर्ज करना'],
    primaryEntity: 'Tehsil Revenue Cadre',
    primaryEntityHi: 'तहसील राजस्व संवर्ग',
    accentColor: 'teal',
  },
  {
    id: 'lao',
    roleCode: 'LAO',
    title: 'Desk Validator / LAO',
    titleHi: 'डेस्क सत्यापनकर्ता / एलएओ',
    subtitle: 'Land Acquisition Officer & Revenue Tehsildar',
    subtitleHi: 'भूमि अधिग्रहण अधिकारी एवं राजस्व तहसीलदार',
    badge: 'Statutory Scrutiny',
    badgeHi: 'वैधानिक संवीक्षा',
    description: 'Scrutinizes Khasra ownership chains, examines public objections under Section 15, drafts Preliminary Awards, and verifies encumbrances.',
    descriptionHi: 'खसरा स्वामित्व श्रृंखला की संवीक्षा, धारा 15 के तहत जनता की आपत्तियों की सुनवाई एवं प्रारंभिक पंचाट तैयार करना।',
    keyResponsibilities: ['Section 15 objection hearing', 'Market value matrix calculation', 'Draft award preparation'],
    keyResponsibilitiesHi: ['धारा 15 आपत्ति सुनवाई', 'सर्कल रेट/बाजार मूल्य गणना', 'प्रारूप पंचाट निर्माण'],
    primaryEntity: 'District Revenue Office',
    primaryEntityHi: 'जिला राजस्व कार्यालय',
    accentColor: 'blue',
  },
  {
    id: 'approver',
    roleCode: 'CALA/DM',
    title: 'Approver / CALA & DM',
    titleHi: 'अनुमोदनकर्ता / सीएएलए एवं डीएम',
    subtitle: 'Competent Authority Land Acquisition & District Magistrate',
    subtitleHi: 'सक्षम प्राधिकारी (भूमि अधिग्रहण) एवं जिला कलेक्टर',
    badge: 'Sanctioning Authority',
    badgeHi: 'स्वीकृति प्राधिकारी',
    description: 'Final statutory sanction under Section 19 declaration, approves the final compensation award under Section 23/30, and authorizes DBT release.',
    descriptionHi: 'धारा 19 घोषणा को अंतिम स्वीकृति, धारा 23/30 के अंतर्गत अंतिम मुआवजा पंचाट अनुमोदन एवं डीबीटी भुगतान जारी करने का आदेश।',
    keyResponsibilities: ['Section 19 statutory signoff', 'Final award sanction', 'PFMS compensation release order'],
    keyResponsibilitiesHi: ['धारा 19 वैधानिक हस्ताक्षर', 'अंतिम पंचाट स्वीकृति', 'पीएफएमएस मुआवजा जारी आदेश'],
    primaryEntity: 'District Administration',
    primaryEntityHi: 'जिला प्रशासन',
    accentColor: 'emerald',
  },
  {
    id: 'executive',
    roleCode: 'EXEC',
    title: 'Executive & Policy Maker',
    titleHi: 'कार्यकारी एवं नीति निर्माता',
    subtitle: 'Ministry of Rural Development, Chief Secretaries, NITI Aayog',
    subtitleHi: 'ग्रामीण विकास मंत्रालय, मुख्य सचिव, नीति आयोग',
    badge: 'National Oversight',
    badgeHi: 'राष्ट्रीय पर्यवेक्षण',
    description: 'Monitors PM-GatiShakti corridor alignments, national fund disbursement velocity, inter-state land acquisition bottlenecks, and policy levers.',
    descriptionHi: 'पीएम-गतिशक्ति गलियारा परियोजनाओं, राष्ट्रीय स्तर पर मुआवजा वितरण एवं अंतर-राज्यीय नीतिगत समन्वय की समीक्षा।',
    keyResponsibilities: ['PM-GatiShakti alignment oversight', 'State progress benchmarking', 'Inter-ministerial resolution'],
    keyResponsibilitiesHi: ['गतिशक्ति परियोजना निगरानी', 'राज्य प्रगति समीक्षा', 'अंतर-मंत्रालयी समन्वय'],
    primaryEntity: 'Union & State Leadership',
    primaryEntityHi: 'केंद्रीय एवं राज्य नेतृत्व',
    accentColor: 'purple',
  },
  {
    id: 'citizen',
    roleCode: 'CITIZEN',
    title: 'Citizen & Landowner',
    titleHi: 'नागरिक एवं भू-स्वामी',
    subtitle: 'Landowner, Farmer, Legal Heir, Affected Family',
    subtitleHi: 'जमीन मालिक, किसान, विधिक उत्तराधिकारी, प्रभावित परिवार',
    badge: 'Public Transparency',
    badgeHi: 'जन पारदर्शिता',
    description: 'Tracks notified land parcel in real-time, submits online objections/claims, views compensation award calculations, and tracks direct DBT credit.',
    descriptionHi: 'अधिग्रहीत जमीन की स्थिति रीयल-टाइम देखना, ऑनलाइन आपत्ति दर्ज करना, मुआवजे की गणना देखना एवं खाते में डीबीटी भुगतान ट्रैक करना।',
    keyResponsibilities: ['Khasra status inquiry', 'E-objection / Claim submission', 'PFMS bank credit tracking'],
    keyResponsibilitiesHi: ['खसरा स्थिति खोज', 'ई-आपत्ति/दावा प्रस्तुति', 'बैंक खाते में मुआवजा ट्रैकिंग'],
    primaryEntity: 'General Public of India',
    primaryEntityHi: 'भारत का सामान्य नागरिक',
    accentColor: 'amber',
  },
  {
    id: 'admin',
    roleCode: 'ADMIN',
    title: 'System Administrator',
    titleHi: 'सिस्टम प्रशासक / नोडल अधिकारी',
    subtitle: 'NIC Nodal Officers, CERT-In Auditors, State Registry Admins',
    subtitleHi: 'एनआईसी नोडल अधिकारी, सीईआरटी-इन ऑडिटर, राज्य रजिस्ट्री एडमिन',
    badge: 'Security & Integrity',
    badgeHi: 'सुरक्षा एवं अखंडता',
    description: 'Manages user credentials via Parichay/MeriPehchan, audits cryptographic access logs, configures state circle rates, and oversees API uptime.',
    descriptionHi: 'परिचय/मेरीपहचान एसएसओ प्रबंधन, क्रिप्टोग्राफिक ऑडिट लॉग की जांच, राज्य सर्किल दरों का विन्यास एवं सुरक्षा निरीक्षण।',
    keyResponsibilities: ['SSO & Parichay role provisioning', 'Audit log tamper monitoring', 'State registry API sync'],
    keyResponsibilitiesHi: ['एसएसओ परिचय भूमिका प्रबंधन', 'ऑडिट लॉग सुरक्षा जांच', 'एपीआई डेटा समन्वय'],
    primaryEntity: 'NIC / MeitY / State DILRMP',
    primaryEntityHi: 'एनआईसी / इलेक्ट्रॉनिकी मंत्रालय',
    accentColor: 'slate',
  },
];

export const TRANSPARENCY_KPIS = [
  {
    id: 'area-notified',
    value: '4,82,590+',
    unit: 'Hectares',
    unitHi: 'हेक्टेयर',
    label: 'Area Notified for National Projects',
    labelHi: 'राष्ट्रीय परियोजनाओं हेतु अधिसूचित क्षेत्रफल',
    subtext: 'Across 1,240+ linear corridors and economic zones',
    subtextHi: '1,240+ राष्ट्रीय राजमार्ग, रेलवे एवं आर्थिक गलियारों में',
    color: 'amber',
  },
  {
    id: 'comp-disbursed',
    value: '₹68,420+ Cr',
    unit: 'Direct PFMS / DBT',
    unitHi: 'प्रत्यक्ष पीएफएमएस / डीबीटी',
    label: 'Compensation Disbursed Directly',
    labelHi: 'प्रत्यक्ष बैंक खातों में अंतरित कुल मुआवजा',
    subtext: 'Zero intermediaries; 100% Aadhaar-seeded transparent payout',
    subtextHi: 'शून्य बिचौलिया; 100% आधार से जुड़े बैंक खातों में',
    color: 'emerald',
  },
  {
    id: 'cases-resolved',
    value: '1,42,830+',
    unit: 'Parcels Awarded',
    unitHi: 'भूखंड पंचाट पूर्ण',
    label: 'Acquisition Cases Resolved',
    labelHi: 'निस्तारित भूमि अधिग्रहण प्रकरण',
    subtext: '92% reduction in Section 15 objections turnaround time',
    subtextHi: 'धारा 15 आपत्तियों के निस्तारण समय में 92% की कमी',
    color: 'sky',
  },
  {
    id: 'sync-rate',
    value: '94.8%',
    unit: 'Cadastral Sync',
    unitHi: 'भू-नक्शा समन्वय',
    label: 'Records Digitized & Geo-Referenced',
    labelHi: 'डिजिटलीकृत एवं भू-संदर्भित भू-अभिलेख',
    subtext: 'Synchronized with Bhunaksha and State Land Registries',
    subtextHi: 'भू-नक्शा एवं राज्य भू-अभिलेखों के साथ लाइव सिंक',
    color: 'indigo',
  },
];

export const SAMPLE_LAND_RECORDS: LandRecordStatus[] = [
  {
    notificationId: 'LA-UP-GBN-2025-0842',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    village: 'Dayanatpur',
    khasraNo: '142/2',
    landownerName: 'Shri Ramswaroop Singh & Smt. Kanti Devi',
    projectAffiliation: 'Noida International Airport (Jewar) Phase II Infrastructure Corridor',
    notifiedAreaHectares: 0.842,
    currentStage: 'Award Inquiry',
    stageIndex: 4,
    compensationCalculated: '₹1,48,60,000',
    solatiumComponent: '₹74,30,000 (100% Solatium included under RFCTLARR Act 2013)',
    dbtPaymentStatus: 'Sanction Order Issued',
    utrReference: 'PFMS-RBI-20250914-99841',
    dateNotified: '14 Jan 2025',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-MH-PUN-2024-1920',
    state: 'Maharashtra',
    district: 'Pune',
    tehsil: 'Haveli',
    village: 'Wagholi',
    khasraNo: '88/A/1',
    landownerName: 'Shri Dnyaneshwar Babanrao Patil',
    projectAffiliation: 'Pune Outer Ring Road Expressway Project - Section 3',
    notifiedAreaHectares: 0.45,
    currentStage: 'Compensation Disbursed',
    stageIndex: 5,
    compensationCalculated: '₹92,40,000',
    solatiumComponent: '₹46,20,000 (100% Solatium & 12% Interest)',
    dbtPaymentStatus: 'Processed via PFMS',
    utrReference: 'PFMS-SBI-20250811-44781',
    dateNotified: '02 Nov 2024',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-HR-SNP-2025-0311',
    state: 'Haryana',
    district: 'Sonipat',
    tehsil: 'Ganaur',
    village: 'Shahpur Turk',
    khasraNo: '412',
    landownerName: 'Shri Virender Kumar & Bros.',
    projectAffiliation: 'Western Dedicated Freight Corridor (WDFC) Yard Expansion',
    notifiedAreaHectares: 1.12,
    currentStage: 'Joint Measurement Survey',
    stageIndex: 2,
    compensationCalculated: '₹2,10,00,000 (Estimated)',
    solatiumComponent: 'Calculated post-JMS final verification',
    dbtPaymentStatus: 'Under Bank Verification',
    utrReference: 'PENDING_SANCTION',
    dateNotified: '28 Feb 2025',
    disputeFlag: false,
  },
  {
    notificationId: 'LA-KA-BLR-2025-0774',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    tehsil: 'Hosakote',
    village: 'Sulibele',
    khasraNo: '29/3',
    landownerName: 'Smt. Lakshmi Venkataramanappa',
    projectAffiliation: 'Bengaluru-Chennai Expressway (NE-7) Link Road',
    notifiedAreaHectares: 0.38,
    currentStage: 'Sec 19 Declaration',
    stageIndex: 3,
    compensationCalculated: '₹84,50,000',
    solatiumComponent: 'RFCTLARR Schedule I Verified',
    dbtPaymentStatus: 'Sanction Order Issued',
    utrReference: 'PFMS-CAN-20250629-10924',
    dateNotified: '10 May 2025',
    disputeFlag: false,
  }
];

export const TICKER_NOTICES = [
  { text: 'Gazette: RFCTLARR Act Section 11(1) notification published for Delhi-Amritsar-Katra Expressway Package 4', textHi: 'राजपत्र: दिल्ली-अमृतसर-कटरा एक्सप्रेसवे पैकेज 4 हेतु धारा 11(1) अधिसूचना जारी' },
  { text: 'Digital India Land Records: 28 States successfully onboarded on ZameenAI Unified RoR Grid', textHi: 'डिजिटल इंडिया भूमि अभिलेख: 28 राज्य ज़मीन एआई एकीकृत आरओआर ग्रिड पर सफलतापूर्वक जुड़े' },
  { text: 'PFMS Direct Disbursal: Over ₹68,000 Crore credited directly to verified Aadhaar-linked farmer accounts', textHi: 'पीएफएमएस प्रत्यक्ष अंतरण: 68,000 करोड़ रुपये से अधिक सीधे किसानों के बैंक खातों में अंतरित' },
  { text: 'DILRMP Advisory: Drone-assisted aerial LiDAR survey completed for 1,200 km railway freight alignment', textHi: 'डीआईएलआरएमपी परामर्श: 1,200 किमी रेल कॉरिडोर हेतु ड्रोन-आधारित लिडार सर्वेक्षण संपन्न' },
];
