"""Canonical permission registry (single vocabulary: MODULE.ACTION).

One registry used by backend guards, frontend parity checks, /auth/roles,
and tests. Do NOT create a second vocabulary elsewhere.

Families: LAND_RECORD, DOCUMENT, DIGITIZATION, OCR, EXTRACTION,
FIELD_VERIFICATION, HITL, WORKFLOW, ACQUISITION, COMPENSATION, RNR,
GIS, REPORT, DASHBOARD/ANALYTICS/PREDICTIVE, AUDIT, USER/ROLE/PERMISSION,
SYSTEM, GRIEVANCE, NOTICE/OBJECTION/CONTESTED/POSSESSION/RECORD (freeze).
Legacy aliases (PROJECT.*, VALIDATION.REVIEW, CORRECTION.REQUEST,
FIELD.VERIFY, OWN.*, DOCUMENT.CREATE) are retained in the same registry
for backward compatibility and mapped to canonical enforcement.
"""
from __future__ import annotations

from app.core.roles import (
    APPROVER,
    CITIZEN,
    DESK_VALIDATOR,
    EXECUTIVE,
    FIELD_OFFICER,
    PIA,
    SYSTEM_ADMIN,
)

# ---------------------------------------------------------------------------
# Canonical permission strings
# ---------------------------------------------------------------------------

LAND_RECORD_READ = "LAND_RECORD.READ"
LAND_RECORD_CREATE = "LAND_RECORD.CREATE"
LAND_RECORD_UPDATE = "LAND_RECORD.UPDATE"
LAND_RECORD_VALIDATE = "LAND_RECORD.VALIDATE"
LAND_RECORD_APPROVE = "LAND_RECORD.APPROVE"
LAND_RECORD_REJECT = "LAND_RECORD.REJECT"

DOCUMENT_READ = "DOCUMENT.READ"
DOCUMENT_UPLOAD = "DOCUMENT.UPLOAD"
DOCUMENT_UPDATE = "DOCUMENT.UPDATE"
DOCUMENT_DELETE = "DOCUMENT.DELETE"
DOCUMENT_DOWNLOAD = "DOCUMENT.DOWNLOAD"

DIGITIZATION_RUN = "DIGITIZATION.RUN"
DIGITIZATION_READ = "DIGITIZATION.READ"

OCR_READ = "OCR.READ"
OCR_PROCESS = "OCR.PROCESS"
OCR_UPDATE = "OCR.UPDATE"
OCR_VALIDATE = "OCR.VALIDATE"

EXTRACTION_READ = "EXTRACTION.READ"
EXTRACTION_UPDATE = "EXTRACTION.UPDATE"

FIELD_VERIFICATION_READ = "FIELD_VERIFICATION.READ"
FIELD_VERIFICATION_CREATE = "FIELD_VERIFICATION.CREATE"
FIELD_VERIFICATION_UPDATE = "FIELD_VERIFICATION.UPDATE"
FIELD_VERIFICATION_SUBMIT = "FIELD_VERIFICATION.SUBMIT"
FIELD_VERIFICATION_APPROVE = "FIELD_VERIFICATION.APPROVE"

HITL_REVIEW = "HITL.REVIEW"

WORKFLOW_READ = "WORKFLOW.READ"
WORKFLOW_ASSIGN = "WORKFLOW.ASSIGN"
WORKFLOW_APPROVE = "WORKFLOW.APPROVE"
WORKFLOW_REJECT = "WORKFLOW.REJECT"
WORKFLOW_RETURN = "WORKFLOW.RETURN"

ACQUISITION_READ = "ACQUISITION.READ"
ACQUISITION_CREATE = "ACQUISITION.CREATE"
ACQUISITION_UPDATE = "ACQUISITION.UPDATE"
ACQUISITION_SUBMIT = "ACQUISITION.SUBMIT"
ACQUISITION_APPROVE = "ACQUISITION.APPROVE"
ACQUISITION_REJECT = "ACQUISITION.REJECT"

COMPENSATION_READ = "COMPENSATION.READ"
COMPENSATION_CALCULATE = "COMPENSATION.CALCULATE"
COMPENSATION_APPROVE = "COMPENSATION.APPROVE"
COMPENSATION_PAYMENT_REQUEST = "COMPENSATION.PAYMENT_REQUEST"

RNR_READ = "RNR.READ"
RNR_CREATE = "RNR.CREATE"
RNR_UPDATE = "RNR.UPDATE"
RNR_APPROVE = "RNR.APPROVE"

GIS_READ = "GIS.READ"
GIS_UPDATE = "GIS.UPDATE"
GIS_EXPORT = "GIS.EXPORT"

REPORT_READ = "REPORT.READ"
REPORT_CREATE = "REPORT.CREATE"
REPORT_EXPORT = "REPORT.EXPORT"

DASHBOARD_READ = "DASHBOARD.READ"
ANALYTICS_READ = "ANALYTICS.READ"
PREDICTIVE_READ = "PREDICTIVE.READ"

AUDIT_READ = "AUDIT.READ"

USER_READ = "USER.READ"
USER_CREATE = "USER.CREATE"
USER_UPDATE = "USER.UPDATE"
USER_DISABLE = "USER.DISABLE"

ROLE_READ = "ROLE.READ"
ROLE_CREATE = "ROLE.CREATE"
ROLE_UPDATE = "ROLE.UPDATE"

PERMISSION_READ = "PERMISSION.READ"
PERMISSION_ASSIGN = "PERMISSION.ASSIGN"

SYSTEM_CONFIGURE = "SYSTEM.CONFIGURE"

GRIEVANCE_CREATE = "GRIEVANCE.CREATE"
GRIEVANCE_READ = "GRIEVANCE.READ"

NOTICE_READ = "NOTICE.READ"
NOTICE_ISSUE = "NOTICE.ISSUE"

OBJECTION_READ = "OBJECTION.READ"
OBJECTION_CREATE = "OBJECTION.CREATE"
OBJECTION_RESOLVE = "OBJECTION.RESOLVE"

CONTESTED_READ = "CONTESTED.READ"
CONTESTED_FLAG = "CONTESTED.FLAG"
CONTESTED_RESOLVE = "CONTESTED.RESOLVE"

POSSESSION_READ = "POSSESSION.READ"
POSSESSION_APPROVE = "POSSESSION.APPROVE"

RECORD_FREEZE = "RECORD.FREEZE"
RECORD_UNFREEZE = "RECORD.UNFREEZE"

EXPORT_DATA = "EXPORT.DATA"

# Legacy strings (same MODULE.ACTION vocabulary, retained for compat).
PROJECT_READ = "PROJECT.READ"
PROJECT_WRITE = "PROJECT.WRITE"
DOCUMENT_CREATE_LEGACY = "DOCUMENT.CREATE"
VALIDATION_REVIEW = "VALIDATION.REVIEW"
CORRECTION_REQUEST = "CORRECTION.REQUEST"
FIELD_VERIFY_LEGACY = "FIELD.VERIFY"
OWN_RECORD_READ = "OWN.RECORD.READ"
OWN_STATUS_READ = "OWN.STATUS.READ"

ALL_PERMISSIONS: frozenset[str] = frozenset({
    LAND_RECORD_READ, LAND_RECORD_CREATE, LAND_RECORD_UPDATE,
    LAND_RECORD_VALIDATE, LAND_RECORD_APPROVE, LAND_RECORD_REJECT,
    DOCUMENT_READ, DOCUMENT_UPLOAD, DOCUMENT_UPDATE, DOCUMENT_DELETE, DOCUMENT_DOWNLOAD,
    DIGITIZATION_RUN, DIGITIZATION_READ,
    OCR_READ, OCR_PROCESS, OCR_UPDATE, OCR_VALIDATE,
    EXTRACTION_READ, EXTRACTION_UPDATE,
    FIELD_VERIFICATION_READ, FIELD_VERIFICATION_CREATE, FIELD_VERIFICATION_UPDATE,
    FIELD_VERIFICATION_SUBMIT, FIELD_VERIFICATION_APPROVE,
    HITL_REVIEW,
    WORKFLOW_READ, WORKFLOW_ASSIGN, WORKFLOW_APPROVE, WORKFLOW_REJECT, WORKFLOW_RETURN,
    ACQUISITION_READ, ACQUISITION_CREATE, ACQUISITION_UPDATE, ACQUISITION_SUBMIT,
    ACQUISITION_APPROVE, ACQUISITION_REJECT,
    COMPENSATION_READ, COMPENSATION_CALCULATE, COMPENSATION_APPROVE,
    COMPENSATION_PAYMENT_REQUEST,
    RNR_READ, RNR_CREATE, RNR_UPDATE, RNR_APPROVE,
    GIS_READ, GIS_UPDATE, GIS_EXPORT,
    REPORT_READ, REPORT_CREATE, REPORT_EXPORT,
    DASHBOARD_READ, ANALYTICS_READ, PREDICTIVE_READ,
    AUDIT_READ,
    USER_READ, USER_CREATE, USER_UPDATE, USER_DISABLE,
    ROLE_READ, ROLE_CREATE, ROLE_UPDATE,
    PERMISSION_READ, PERMISSION_ASSIGN,
    SYSTEM_CONFIGURE,
    GRIEVANCE_CREATE, GRIEVANCE_READ,
    NOTICE_READ, NOTICE_ISSUE,
    OBJECTION_READ, OBJECTION_CREATE, OBJECTION_RESOLVE,
    CONTESTED_READ, CONTESTED_FLAG, CONTESTED_RESOLVE,
    POSSESSION_READ, POSSESSION_APPROVE,
    RECORD_FREEZE, RECORD_UNFREEZE,
    EXPORT_DATA,
    PROJECT_READ, PROJECT_WRITE, DOCUMENT_CREATE_LEGACY,
    VALIDATION_REVIEW, CORRECTION_REQUEST, FIELD_VERIFY_LEGACY,
    OWN_RECORD_READ, OWN_STATUS_READ,
})

# ---------------------------------------------------------------------------
# Role -> permissions (canonical matrix).
# Operational boundaries:
#  PIA create/init | Field ground-truth | LAO validation |
#  Approver legal authorization | Executive read-heavy | Citizen own-only
# ---------------------------------------------------------------------------

ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    SYSTEM_ADMIN: frozenset({"*"}),
    PIA: frozenset({
        LAND_RECORD_READ, LAND_RECORD_CREATE,
        DOCUMENT_READ, DOCUMENT_UPLOAD, DOCUMENT_DOWNLOAD,
        DOCUMENT_CREATE_LEGACY,
        DIGITIZATION_READ, DIGITIZATION_RUN,
        OCR_READ, OCR_PROCESS,
        EXTRACTION_READ,
        ACQUISITION_READ, ACQUISITION_CREATE, ACQUISITION_UPDATE, ACQUISITION_SUBMIT,
        PROJECT_READ, PROJECT_WRITE,
        GIS_READ, GIS_UPDATE,
        WORKFLOW_READ,
        REPORT_READ, REPORT_CREATE,
        DASHBOARD_READ,
        FIELD_VERIFICATION_READ, FIELD_VERIFICATION_SUBMIT,
        OBJECTION_CREATE, OBJECTION_READ,
        GRIEVANCE_READ,
    }),
    FIELD_OFFICER: frozenset({
        LAND_RECORD_READ,
        DOCUMENT_READ, DOCUMENT_UPLOAD, DOCUMENT_DOWNLOAD,
        DOCUMENT_CREATE_LEGACY,
        DIGITIZATION_READ,
        OCR_READ,
        EXTRACTION_READ,
        FIELD_VERIFICATION_READ, FIELD_VERIFICATION_CREATE,
        FIELD_VERIFICATION_UPDATE, FIELD_VERIFICATION_SUBMIT,
        FIELD_VERIFY_LEGACY,
        GIS_READ,
        WORKFLOW_READ,
        GRIEVANCE_READ,
    }),
    DESK_VALIDATOR: frozenset({
        LAND_RECORD_READ, LAND_RECORD_UPDATE, LAND_RECORD_VALIDATE,
        DOCUMENT_READ, DOCUMENT_UPLOAD, DOCUMENT_UPDATE, DOCUMENT_DOWNLOAD,
        DIGITIZATION_READ, DIGITIZATION_RUN,
        OCR_READ, OCR_PROCESS, OCR_UPDATE, OCR_VALIDATE,
        EXTRACTION_READ, EXTRACTION_UPDATE,
        VALIDATION_REVIEW, CORRECTION_REQUEST,
        HITL_REVIEW,
        WORKFLOW_READ, WORKFLOW_RETURN, WORKFLOW_ASSIGN,
        GIS_READ, GIS_UPDATE,
        REPORT_READ,
        ACQUISITION_READ,
        COMPENSATION_READ, COMPENSATION_CALCULATE,
        RNR_READ,
        OBJECTION_READ,
        GRIEVANCE_READ,
        FIELD_VERIFICATION_READ,
    }),
    APPROVER: frozenset({
        LAND_RECORD_READ, LAND_RECORD_APPROVE, LAND_RECORD_REJECT,
        DOCUMENT_READ, DOCUMENT_DOWNLOAD,
        DIGITIZATION_READ,
        OCR_READ, OCR_VALIDATE,
        EXTRACTION_READ,
        HITL_REVIEW,
        WORKFLOW_READ, WORKFLOW_APPROVE, WORKFLOW_REJECT, WORKFLOW_RETURN, WORKFLOW_ASSIGN,
        ACQUISITION_READ, ACQUISITION_APPROVE, ACQUISITION_REJECT,
        COMPENSATION_READ, COMPENSATION_CALCULATE, COMPENSATION_APPROVE,
        COMPENSATION_PAYMENT_REQUEST,
        RNR_READ, RNR_APPROVE,
        GIS_READ, GIS_UPDATE,
        REPORT_READ, REPORT_CREATE,
        DASHBOARD_READ, ANALYTICS_READ,
        NOTICE_READ, NOTICE_ISSUE,
        OBJECTION_READ, OBJECTION_RESOLVE,
        CONTESTED_READ, CONTESTED_FLAG, CONTESTED_RESOLVE,
        POSSESSION_READ, POSSESSION_APPROVE,
        RECORD_FREEZE, RECORD_UNFREEZE,
        FIELD_VERIFICATION_READ, FIELD_VERIFICATION_APPROVE,
    }),
    EXECUTIVE: frozenset({
        LAND_RECORD_READ,
        DOCUMENT_READ, DOCUMENT_DOWNLOAD,
        DIGITIZATION_READ,
        OCR_READ,
        EXTRACTION_READ,
        ACQUISITION_READ,
        COMPENSATION_READ,
        RNR_READ,
        GIS_READ, GIS_EXPORT,
        REPORT_READ, REPORT_EXPORT,
        EXPORT_DATA,
        DASHBOARD_READ, ANALYTICS_READ, PREDICTIVE_READ,
        WORKFLOW_READ,
        NOTICE_READ,
        OBJECTION_READ,
        CONTESTED_READ,
        POSSESSION_READ,
        FIELD_VERIFICATION_READ,
    }),
    CITIZEN: frozenset({
        LAND_RECORD_READ,
        DOCUMENT_READ, DOCUMENT_DOWNLOAD,
        ACQUISITION_READ,
        COMPENSATION_READ,
        RNR_READ,
        GIS_READ,
        OBJECTION_CREATE, OBJECTION_READ,
        GRIEVANCE_CREATE, GRIEVANCE_READ,
        OWN_RECORD_READ, OWN_STATUS_READ,
        FIELD_VERIFICATION_READ,
    }),
}


def has_permission(role: str, permission: str) -> bool:
    perms = ROLE_PERMISSIONS.get(role, frozenset())
    return "*" in perms or permission in perms


def permissions_for(role: str) -> frozenset[str]:
    if role == SYSTEM_ADMIN:
        return frozenset(ALL_PERMISSIONS | {"*"})
    return ROLE_PERMISSIONS.get(role, frozenset())


def is_known_permission(permission: str) -> bool:
    return permission == "*" or permission in ALL_PERMISSIONS
